let supa=null,session=null,profile=null,user=null;
const $=id=>document.getElementById(id),app=$('app');
const reserved=new Set(['admin','api','login','register','dashboard','settings','support','profile','privacy','terms','favicon','assets','static']);
async function boot(){try{const c=await (await fetch('/api/config/public',{cache:'no-store'})).json();if(!c.supabaseUrl||!c.supabasePublishableKey)return fail('ยังไม่ได้ตั้งค่า Supabase');supa=window.supabase.createClient(c.supabaseUrl,c.supabasePublishableKey);const me=await (await fetch('/api/auth/me',{cache:'no-store'})).json();const ss=await supa.auth.getSession();session=ss.data.session;user=me.user;if(!me.loggedIn&&session){await fetch('/api/auth/bootstrap',{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({username:session.user.user_metadata?.username,name:session.user.user_metadata?.display_name})});const fresh=await (await fetch('/api/auth/me',{cache:'no-store'})).json();user=fresh.user;me.loggedIn=fresh.loggedIn}if(!me.loggedIn)return location.href='/login';await loadProfile();render('home')}catch(e){fail(e.message||'เชื่อมต่อไม่ได้')}}
async function api(url,opt={}){opt.headers={...(opt.headers||{})};if(session?.access_token)opt.headers.Authorization=`Bearer ${session.access_token}`;const r=await fetch(url,opt);const d=await r.json();if(!r.ok)throw Error(d.message||'เกิดข้อผิดพลาด');return d}
async function loadProfile(){const d=await api('/api/profile');profile=d.profile||{};$('public').href=profile.username?`/${encodeURIComponent(profile.username)}`:'#';if(!profile.username)return render('profile',true)}
function fail(x){app.innerHTML=`<div class="panel"><h2>เชื่อมต่อไม่ได้</h2><p class="muted">${esc(x)}</p></div>`}
function render(page,force=false){$('heading').textContent={home:'แดชบอร์ด',profile:'โปรไฟล์',stats:'สถิติ',card:'Profile Card',links:'ลิงก์ & เพลง'}[page]||'แดชบอร์ด';if(page==='profile'||force)return profilePage();if(page==='stats')return statsPage();if(page==='links')return linksPage();if(page==='card')return cardPage();return homePage()}
function homePage(){const links=profile?.links||[],music=profile?.music||[];app.innerHTML=`<div class="grid"><div class="stat"><span class="muted">Links</span><b>${links.length}</b></div><div class="stat"><span class="muted">เพลง</span><b>${music.length}</b></div><div class="stat"><span class="muted">Username</span><b>@${esc(profile?.username||'ยังไม่ได้ตั้ง')}</b></div></div><div class="panel" style="margin-top:14px"><h2>ยินดีต้อนรับ</h2><p class="muted">บัญชีนี้เข้าถึงได้เฉพาะข้อมูลของคุณเอง และไม่มีสิทธิ์เข้าถึงระบบ Admin</p></div>`}
function profilePage(){app.innerHTML=`<div class="panel"><h2>ตั้งค่าโปรไฟล์</h2><p class="muted">Username จะกลายเป็นลิงก์สาธารณะของคุณ และห้ามซ้ำกับคนอื่น</p><div class="grid"><label>Username<input class="input" id="puser" value="${esc(profile?.username||'')}" maxlength="40"></label><label>ชื่อที่แสดง<input class="input" id="pname" value="${esc(profile?.displayName||profile?.name||'')}" maxlength="80"></label><label>Bio<input class="input" id="pbio" value="${esc(profile?.bio||'')}" maxlength="300"></label></div><div id="check" class="muted" style="margin-top:12px"></div><button class="btn" id="saveProfile">บันทึกโปรไฟล์</button></div>`;const input=$('puser');let timer;input.oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>checkUsername(input.value),250)};checkUsername(input.value);$('saveProfile').onclick=saveProfile}
async function checkUsername(v){const u=String(v||'').trim().toLowerCase(),out=$('check');if(!out)return;if(!/^[a-z0-9._-]{2,40}$/.test(u)||reserved.has(u)){out.className='bad';out.textContent='Username ไม่ถูกต้องหรือสงวนไว้';return}try{const r=await fetch('/api/profile?username='+encodeURIComponent(u));out.className=r.ok?'bad':'ok';out.textContent=r.ok?'Username นี้ถูกใช้งานแล้ว':'✓ Username นี้สามารถใช้งานได้'}catch{out.textContent='ตรวจสอบไม่ได้'}}
async function saveProfile(){const username=$('puser').value.trim().toLowerCase();if(reserved.has(username)||!/^[a-z0-9._-]{2,40}$/.test(username))return;const body={...profile,username,name:$('pname').value.trim(),displayName:$('pname').value.trim(),bio:$('pbio').value.trim()};try{const d=await api('/api/profile',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});profile=d.profile;await loadProfile();render('profile');toast('บันทึกโปรไฟล์แล้ว')}catch(e){toast(e.message,true)}}
async function statsPage(){try{const d=await api('/api/analytics');app.innerHTML=`<div class="grid"><div class="stat"><span class="muted">เข้าชมโปรไฟล์</span><b>${d.totalProfileViews||0}</b></div><div class="stat"><span class="muted">คลิก Link</span><b>${d.totalLinkClicks||0}</b></div><div class="stat"><span class="muted">วันนี้</span><b>${d.todayViews||0}</b></div></div><div class="panel" style="margin-top:14px"><h2>สถิติของฉัน</h2><p class="muted">ข้อมูลสถิติถูกแยกตามบัญชีและอ่านได้เฉพาะเจ้าของโปรไฟล์</p></div>`}catch(e){app.innerHTML=`<div class="panel">${esc(e.message)}</div>`}}
function linksPage(){const links=profile.links||[],music=profile.music||[];app.innerHTML=`<div class="panel"><h2>ลิงก์ & เพลง</h2><p class="muted">จัดการข้อมูลของคุณเองได้ที่นี่ ข้อมูลไม่ปะปนกับผู้ใช้อื่น</p><div class="grid"><div class="stat"><span class="muted">Links</span><b>${links.length}</b></div><div class="stat"><span class="muted">เพลง</span><b>${music.length}</b></div><div class="stat"><span class="muted">GIF ประจำ Link</span><b>พร้อมใช้</b></div></div></div>`}
function cardPage(){app.innerHTML=`<div class="panel"><h2>Profile Card</h2><p class="muted">ตั้งค่า Profile Card ของคุณโดยเฉพาะ ระบบจะไม่กระทบโปรไฟล์อื่น</p><button class="btn" id="loadCard">โหลดการตั้งค่า</button><div id="cardState" class="muted" style="margin-top:12px"></div></div>`;$('loadCard').onclick=async()=>{try{const d=await api('/api/profile-card');$('cardState').textContent=`โหมด: ${d.profileCard?.mode||'transparent'} • Blur: ${d.profileCard?.blur??0}px`}catch(e){$('cardState').textContent=e.message}}}
function toast(text,bad=false){let x=document.getElementById('toast');if(!x){x=document.createElement('div');x.id='toast';x.style='position:fixed;right:20px;bottom:20px;padding:12px 16px;border:1px solid #ffffff20;border-radius:12px;background:#111827ee;color:#fff;z-index:99';document.body.appendChild(x)}x.textContent=text;x.style.borderColor=bad?'#fb7185':'#8b5cf6';clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.remove(),2600)}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
document.querySelectorAll('aside button[data-page]').forEach(b=>b.onclick=()=>render(b.dataset.page));$('logout').onclick=async()=>{try{if(supa)await supa.auth.signOut();await fetch('/api/auth/logout',{method:'POST'})}finally{location.href='/login'}};boot();
