let supa=null,session=null,profile=null;
const $=id=>document.getElementById(id),app=$('app');
const reserved=new Set(['admin','api','login','register','dashboard','settings','support','profile','privacy','terms','favicon','assets','static']);
async function boot(){const c=await (await fetch('/api/config/public')).json();if(!c.supabaseUrl||!c.supabasePublishableKey)return fail('ยังไม่ได้ตั้งค่า Supabase');supa=window.supabase.createClient(c.supabaseUrl,c.supabasePublishableKey);const s=await supa.auth.getSession();session=s.data.session;if(!session)return location.href='/user-auth.html';await loadProfile();render('home');}
async function api(url,opt={}){opt.headers={...(opt.headers||{}),Authorization:`Bearer ${session.access_token}`};const r=await fetch(url,opt);const d=await r.json();if(!r.ok)throw Error(d.message||'เกิดข้อผิดพลาด');return d}
async function loadProfile(){const d=await api('/api/profile');profile=d.profile||{};$('public').href=profile.username?`/u/${encodeURIComponent(profile.username)}`:'#';if(!profile.username)return render('profile',true)}
function fail(x){app.innerHTML=`<div class="panel"><h2>เชื่อมต่อไม่ได้</h2><p class="muted">${x}</p></div>`}
function render(page,force=false){$('heading').textContent={home:'แดชบอร์ด',profile:'โปรไฟล์',stats:'สถิติ',card:'Profile Card',links:'ลิงก์ & เพลง'}[page]||'แดชบอร์ด';if(page==='profile'||force)return profilePage();if(page==='stats')return statsPage();if(page==='links')return linksPage();if(page==='card')return cardPage();return homePage()}
function homePage(){const links=profile?.links||[],music=profile?.music||[];app.innerHTML=`<div class="grid"><div class="stat"><span class="muted">Links</span><b>${links.length}</b></div><div class="stat"><span class="muted">เพลง</span><b>${music.length}</b></div><div class="stat"><span class="muted">Username</span><b>@${esc(profile?.username||'ยังไม่ได้ตั้ง')}</b></div></div><div class="panel" style="margin-top:14px"><h2>เริ่มต้นใช้งาน</h2><p class="muted">จัดการโปรไฟล์, Profile Card และลิงก์ & เพลงจากเมนูด้านซ้าย</p></div>`}
function profilePage(){app.innerHTML=`<div class="panel"><h2>ตั้งค่าโปรไฟล์</h2><p class="muted">Username จะกลายเป็นลิงก์สาธารณะของคุณ และห้ามซ้ำกับคนอื่น</p><div class="grid"><label>Username<input class="input" id="puser" value="${esc(profile?.username||'')}" maxlength="40"></label><label>ชื่อที่แสดง<input class="input" id="pname" value="${esc(profile?.displayName||profile?.name||'')}" maxlength="80"></label><label>Bio<input class="input" id="pbio" value="${esc(profile?.bio||'')}" maxlength="300"></label></div><div id="check" class="muted" style="margin-top:12px"></div><button class="btn" id="saveProfile">บันทึกโปรไฟล์</button></div>`;const input=$('puser');let timer;input.oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>checkUsername(input.value),250)};checkUsername(input.value);$('saveProfile').onclick=saveProfile}
async function checkUsername(v){const u=String(v||'').trim().toLowerCase();const out=$('check');if(!out)return;if(!/^[a-z0-9_-]{2,40}$/.test(u)){out.className='bad';out.textContent='Username ต้องเป็น a-z, 0-9, _ หรือ - ยาว 2-40 ตัว';return}if(reserved.has(u)){out.className='bad';out.textContent='ชื่อนี้สงวนไว้สำหรับระบบ';return}try{const r=await fetch('/api/profile?username='+encodeURIComponent(u));out.className='ok';out.textContent=r.ok?'ชื่อนี้ถูกใช้งานแล้ว':'✓ Username นี้สามารถใช้งานได้'}catch{out.textContent='ตรวจสอบไม่ได้'}}
async function saveProfile(){const username=$('puser').value.trim().toLowerCase();if(reserved.has(username)||!/^[a-z0-9_-]{2,40}$/.test(username))return;const old=profile.username;const body={...profile,username,name:$('pname').value.trim(),displayName:$('pname').value.trim(),bio:$('pbio').value.trim()};try{const d=await api('/api/profile',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});profile=d.profile;await loadProfile();render('profile');}catch(e){alert(e.message)} }
async function statsPage(){try{const d=await api('/api/analytics');app.innerHTML=`<div class="grid"><div class="stat"><span class="muted">เข้าชมโปรไฟล์</span><b>${d.totalProfileViews||0}</b></div><div class="stat"><span class="muted">คลิก Link</span><b>${d.totalLinkClicks||0}</b></div><div class="stat"><span class="muted">วันนี้</span><b>${d.todayViews||0}</b></div></div>`}catch(e){app.innerHTML=`<div class="panel">${e.message}</div>`}}
function linksPage(){app.innerHTML=`<div class="panel"><h2>ลิงก์ & เพลง</h2><p class="muted">ระบบนี้จะเชื่อมกับ Link และ Music เดิมของ LinkBio โดยข้อมูลของคุณแยกจากผู้ใช้อื่น</p><div class="grid"><div class="stat"><span class="muted">Links</span><b>${(profile.links||[]).length}</b></div><div class="stat"><span class="muted">เพลง</span><b>${(profile.music||[]).length}</b></div><div class="stat"><span class="muted">GIF ต่อ Link</span><b>พร้อมใช้</b></div></div></div>`}
function cardPage(){app.innerHTML=`<div class="panel"><h2>Profile Card</h2><p class="muted">หน้านี้เตรียมไว้สำหรับนำระบบ Profile Card เดิมมาเชื่อมกับ User ของแต่ละคน</p><button class="btn" onclick="render('home')">กลับแดชบอร์ด</button></div>`}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
document.querySelectorAll('aside button[data-page]').forEach(b=>b.onclick=()=>render(b.dataset.page));$('logout').onclick=async()=>{await supa.auth.signOut();location.href='/user-auth.html'};boot();
