[build]
publish = "."
functions = "functions"

[functions]
node_bundler = "esbuild"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200

[[redirects]]
from = "/admin.html"
to = "/admin/index.html"
status = 200

[[redirects]]
from = "/u/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/database/*"
to = "/404.html"
status = 404

[[redirects]]
from = "/server.js"
to = "/404.html"
status = 404

[[redirects]]
from = "/package*.json"
to = "/404.html"
status = 404

[[redirects]]
from = "/.env*"
to = "/404.html"
status = 404

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
