const express=require('express');
const path=require('path');const fs=require('fs');const crypto=require('crypto');const multer=require('multer');
const app=express();const PORT=Number(process.env.PORT)||3000;const ROOT=__dirname;
const DB=path.join(ROOT,'database');const UP=path.join(ROOT,'uploads');
const files={profile:path.join(DB,'profile.json'),links:path.join(DB,'links.json'),music:path.join(DB,'music.json'),profileCard:path.join(DB,'profileCard.json'),background:path.join(DB,'background.json'),appearance:path.join(DB,'appearance.json'),visualizer:path.join(DB,'visualizer.json'),branding:path.join(DB,'branding.json'),analytics:path.join(DB,'analytics.json'),settings:path.join(DB,'settings.json')};
for(const d of [DB,UP,path.join(UP,'avatars'),path.join(UP,'covers'),path.join(UP,'music')])fs.mkdirSync(d,{recursive:true});
const defaults={
profile:{name:'Your Name',username:'username',displayName:'Your Name',bio:'สร้าง Link Bio ของคุณ',bioLines:'',align:'center',font:'Prompt',fontSize:16,fontWeight:600,letterSpacing:0,lineHeight:1.5,status:'Online',statusEmoji:'●',verified:false,verifiedColor:'#60a5fa',avatar:'',avatarCrop:50,avatarZoom:1,avatarPosition:'center',avatarBorder:true,avatarBorderWidth:3,avatarGlow:true,avatarShadow:true,avatarShape:'circle',cover:'',coverPosition:'center',coverOpacity:1,coverBlur:0,coverOverlay:'',cardWidth:480,cardRadius:30,cardShadow:true,cardBlur:24,cardTransparency:.72,spacing:10,animation:'smooth',entrance:'fade',hover:'lift',visibility:true,customCss:'',seoTitle:'LinkBio',seoDescription:'My LinkBio',ogImage:'',favicon:'',accent:'#a855f7',textColor:'#fff',secondary:'#aaa',background:'#08080d',language:'th',timezone:'Asia/Bangkok'},
appearance:{backgroundType:'solid',backgroundColor:'#08080d',gradientColors:['#4b1c77','#08080d'],gradientAngle:135,backgroundImage:'',backgroundGif:'',backgroundVideo:'',backgroundOpacity:1,backgroundBlur:0,videoOpacity:1,videoLoop:true,videoMute:true,overlay:'',overlayOpacity:.2,effects:{particles:true,rain:false,snow:false,meteor:false,stars:false,neonGlow:true,grid:false,aurora:false,fog:false,floatingParticles:true,borderGlow:true,glassBlur:true},effectIntensity:.7,particleCount:40,particleSpeed:1,particleSize:2,performanceMode:false},
visualizer:{enabled:true,mode:'bars',sensitivity:1,smoothing:.78,barCount:34,barWidth:4,barGap:3,height:42,glow:true,opacity:.9,speed:1,frequencyRange:'full',bass:1,mid:1,treble:1,color:'#a855f7',gradient:['#e879f9','#818cf8'],rotation:0,mirror:false,responsive:true},
branding:{enabled:true,text:'Dekkhong',icon:'◆',position:'under-avatar',size:10,color:'#39ff14',neonColor:'#39ff14',glowIntensity:1,animation:'pulse',opacity:1,border:true,radius:999,animationSpeed:1},
profileCard:{enabled:true,mode:'transparent',backgroundColor:'#8b5cf6',opacity:.25,borderColor:'#ffffff',borderOpacity:.15,borderWidth:1,borderRadius:24,blur:18,backdropBlur:18,shadow:true,shadowOpacity:.35,shadowIntensity:.35,innerShadow:false,glow:true,glowColor:'#8b5cf6',glowIntensity:.4,gradientBorder:false,softGlow:true,hoverGlow:true,hoverScale:false,animation:'fade',animationEnabled:true,animationSpeed:.5,animationIntensity:1,hoverEffect:'glow'},
background:{enabled:true,preset:'floating-particles',intensity:.7,speed:1,opacity:.9,quality:'auto',performanceMode:false,interaction:true,settings:{}},
settings:{publicEnabled:true,adminSessionHours:12,performanceMode:false},links:[],music:[],analytics:{profileViews:0,viewsByDay:{},clicksByLink:{},clicksByDay:{},activity:[],lastUpdate:null}
};
function clone(x){return JSON.parse(JSON.stringify(x));}function ensure(k){if(!fs.existsSync(files[k]))fs.writeFileSync(files[k],JSON.stringify(defaults[k],null,2));}
for(const k of Object.keys(files))ensure(k);
function read(k){try{return JSON.parse(fs.readFileSync(files[k],'utf8'));}catch(e){const bak=files[k]+'.bak';try{return JSON.parse(fs.readFileSync(bak,'utf8'));}catch{return clone(defaults[k]);}}}
let publicCache=null;
const publicClients=new Set();
function publicSnapshot(){if(publicCache)return publicCache;publicCache={profile:read('profile'),links:read('links'),music:read('music'),appearance:read('appearance'),visualizer:read('visualizer'),branding:read('branding'),profileCard:read('profileCard'),backgroundSettings:read('background')};return publicCache;}
function publicChanged(k){publicCache=null;if(!['profile','links','music','appearance','visualizer','branding','profileCard','background'].includes(k))return;const payload=JSON.stringify({type:'profile-updated',key:k});for(const client of publicClients){try{client.write(`event: update\\ndata: ${payload}\\n\\n`)}catch{publicClients.delete(client)}}}
function write(k,x){const json=JSON.stringify(x,null,2);JSON.parse(json);const bak=files[k]+'.bak',tmp=files[k]+'.tmp';try{if(fs.existsSync(files[k]))fs.copyFileSync(files[k],bak);}catch{}fs.writeFileSync(tmp,json);fs.renameSync(tmp,files[k]);publicChanged(k);}
function patch(k,obj){const x=read(k);const n={...x,...obj};write(k,n);return n;}
function clean(v,n=500){return String(v??'').trim().slice(0,n)}
function urlOK(v){try{const u=new URL(v);return ['http:','https:'].includes(u.protocol)}catch{return false}}
function hex(v){return /^#[0-9a-f]{6}$/i.test(String(v||''))}
function num(v,min,max){const n=Number(v);return Number.isFinite(n)&&n>=min&&n<=max}
function validateProfileCard(b){if(typeof b!=='object'||!b)return 'ข้อมูล Profile Card ไม่ถูกต้อง';if(!['transparent','solid'].includes(String(b.mode)))return 'โหมด Profile Card ไม่ถูกต้อง';b.mode=String(b.mode);b.animation=({'fade-in':'fade','slideUp':'slide-up','scaleIn':'scale-in','blurReveal':'blur-reveal','glowReveal':'glow-reveal','softPulse':'soft-pulse'}[String(b.animation)]||String(b.animation||'fade')).toLowerCase();b.hoverEffect=({'borderGlow':'border-glow','shadowIncrease':'shadow-increase'}[String(b.hoverEffect)]||String(b.hoverEffect||'none')).toLowerCase();for(const c of ['backgroundColor','borderColor','glowColor'])if(!hex(b[c]))return 'ค่าสี Profile Card ไม่ถูกต้อง';for(const [v,min,max] of [['opacity',0,1],['borderOpacity',0,1],['shadowOpacity',0,1],['shadowIntensity',0,1],['glowIntensity',0,1],['animationSpeed',.05,4],['animationIntensity',0,1]])if(!num(b[v],min,max))return 'ค่าความเข้ม Profile Card ไม่ถูกต้อง';for(const [v,min,max] of [['borderWidth',0,5],['borderRadius',0,50],['blur',0,30],['backdropBlur',0,30]])if(!num(b[v],min,max))return 'ค่าขนาด Profile Card ไม่ถูกต้อง';if(typeof b.enabled!=='boolean'||typeof b.shadow!=='boolean'||typeof b.glow!=='boolean')return 'ค่า Toggle Profile Card ไม่ถูกต้อง';if(!['none','fade','slide-up','scale-in','blur-reveal','glow-reveal','floating','soft-pulse'].includes(b.animation))return 'Animation Profile Card ไม่ถูกต้อง';if(!['none','glow','lift','scale','float','border-glow','shadow-increase'].includes(b.hoverEffect))return 'Hover Effect ไม่ถูกต้อง';return null}
function validateProfile(b){if(typeof b!=='object'||!b)return 'ข้อมูลโปรไฟล์ไม่ถูกต้อง';if(!clean(b.name,80)||!clean(b.username,40)||!clean(b.displayName,80))return 'ชื่อโปรไฟล์/Username ไม่ถูกต้อง';if(!/^[a-zA-Z0-9._-]{2,40}$/.test(clean(b.username,40)))return 'Username ต้องเป็นตัวอักษร ตัวเลข . _ - เท่านั้น';if(!num(b.fontSize,10,48)||!num(b.fontWeight,300,900))return 'ค่าตัวอักษรไม่ถูกต้อง';if(!hex(b.accent)||!hex(b.textColor)||!hex(b.secondary)||!hex(b.background))return 'ค่าสีไม่ถูกต้อง';if(typeof b.verified!=='boolean')return 'ค่า Verified ไม่ถูกต้อง';if(!['inline'].includes(b.verifiedPosition))return 'ตำแหน่ง Verified ไม่ถูกต้อง';if(!['none','check','pulse','glow','float','shine'].includes(b.verifiedAnimation))return 'Animation Verified ไม่ถูกต้อง';if(!num(b.verifiedSize,8,24)||!num(b.verifiedGlow,0,3)||!num(b.verifiedAnimationSpeed,.2,4))return 'ค่าการแสดง Verified ไม่ถูกต้อง';return null}
function yt(v){try{const u=new URL(v);let id=u.searchParams.get('v');if(u.hostname==='youtu.be')id=u.pathname.slice(1);if(!id&&u.pathname.startsWith('/shorts/'))id=u.pathname.split('/')[2];return id&&/^[\w-]{11}$/.test(id)?id:null}catch{return null}}
function siteIcon(v){try{const h=new URL(/^https?:\/\//i.test(v)?v:'https://'+v).hostname.replace(/^www\./,'').toLowerCase();const m=[['instagram.com','instagram'],['tiktok.com','tiktok'],['youtube.com','youtube'],['youtu.be','youtube'],['facebook.com','facebook'],['x.com','x'],['twitter.com','x'],['discord.com','discord'],['discord.gg','discord'],['twitch.tv','twitch'],['github.com','github'],['telegram.me','telegram'],['t.me','telegram'],['line.me','line'],['spotify.com','spotify'],['steampowered.com','steam'],['reddit.com','reddit'],['pinterest.com','pinterest'],['linkedin.com','linkedin']];return (m.find(([d])=>h===d||h.endsWith('.'+d))||[])[1]||'globe'}catch{return 'globe'}}
function day(){return new Date().toISOString().slice(0,10)}
app.disable('x-powered-by');app.use(express.json({limit:'2mb'}));app.use(express.urlencoded({extended:true,limit:'2mb'}));
app.use('/uploads',express.static(UP));app.use('/admin',express.static(path.join(ROOT,'frontend','admin')));app.use('/profile',express.static(path.join(ROOT,'frontend','profile')));app.get('/profile-stickers.js',(_q,r)=>r.sendFile(path.join(ROOT,'frontend','profile-stickers.js')));app.get('/profile-stickers.css',(_q,r)=>r.sendFile(path.join(ROOT,'frontend','profile-stickers.css')));app.use('/music-player',express.static(path.join(ROOT,'frontend','music-player')));app.use('/visualizer',express.static(path.join(ROOT,'frontend','visualizer')));
// Root deploy assets: keep the public site self-contained for Netlify and localhost.
app.get('/style.css',(q,r)=>r.sendFile(path.join(ROOT,'style.css')));app.get('/app.js',(q,r)=>r.sendFile(path.join(ROOT,'app.js')));

const { enabled: supabaseEnabled, supabase } = require('./lib/supabase');
const { createClient } = require('@supabase/supabase-js');
const serviceKey=String(process.env.SUPABASE_SERVICE_ROLE_KEY||'').trim();
const adminClient=(process.env.SUPABASE_URL&&serviceKey)?createClient(process.env.SUPABASE_URL,serviceKey,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}}):null;
const userSessions=new Map();
const PUBLIC_SECTIONS=['profile','links','music','appearance','visualizer','branding','profileCard','background'];
function publicUsername(req){const q=String(req.query?.username||'').trim().replace(/^@/,'');if(q)return q;const ref=String(req.headers.referer||'');const m=ref.match(/\/u\/([^/?#]+)/);return m?decodeURIComponent(m[1]):'';}
async function findUserByUsername(username){if(!supabaseEnabled||!supabase)return null;const {data,error}=await supabase.from('public_profiles').select('user_id,data,updated_at').ilike('data->>username',username).maybeSingle();if(error)throw error;return data||null;}
async function sectionsFor(userId){const {data,error}=await supabase.from('user_data').select('section,data').eq('user_id',userId).in('section',PUBLIC_SECTIONS);if(error)throw error;const out={};for(const row of data||[])out[row.section]=row.data;return out;}
async function sectionFor(userId,section,fallback={}){const {data,error}=await supabase.from('user_data').select('data').eq('user_id',userId).eq('section',section).maybeSingle();if(error)throw error;return data?.data??fallback;}
async function saveSection(userId,section,value){const {data,error}=await supabase.from('user_data').upsert({user_id:userId,section,data:value},{onConflict:'user_id,section'}).select('data').single();if(error)throw error;return data.data;}
async function resolveSession(req){const token=cookies(req).linkbio_session;const s=token&&userSessions.get(token);if(s&&s.exp>Date.now())return s.userId;if(s)userSessions.delete(token);return null;}
let ownerUserId=null;
async function getOwnerId(){
 if(ownerUserId)return ownerUserId;if(!adminClient)return null;
 const email=String(process.env.SUPABASE_OWNER_EMAIL||'owner@linkbio.local').trim().toLowerCase();
 const {data,error}=await adminClient.auth.admin.listUsers({page:1,perPage:1000});if(error)throw error;
 ownerUserId=(data.users||[]).find(u=>u.email?.toLowerCase()===email)?.id||null;return ownerUserId;
}
async function resolveUser(req,allowPublic=true){
 const sid=await resolveSession(req);if(sid)return sid;
 if(!allowPublic)return null;
 const username=publicUsername(req);if(username){const p=await findUserByUsername(username);return p?.user_id||null;}
 return getOwnerId();
}
async function requireOwner(req,res){if(!supabaseEnabled||!adminClient)return {error:'Supabase server key is not configured'};const id=await resolveUser(req,false);if(!id)return {error:'กรุณาเข้าสู่ระบบ'};return {id};}
function publicPayload(s){return {success:true,profile:{...(s.profile||{}),links:s.links||[],music:s.music||[],appearance:s.appearance||{},visualizer:s.visualizer||{},branding:s.branding||{},profileCard:s.profileCard||{},backgroundSettings:s.background||{}}};}
async function handleSupabase(req,res,next){
  if(!supabaseEnabled||!supabase)return next();
  try{
    if(req.path==='/api/admin/me'&&req.method==='GET'){const id=await resolveSession(req);return res.json({success:true,loggedIn:Boolean(id)});}
    if(req.path==='/api/admin/logout'&&req.method==='POST'){const t=cookies(req).linkbio_session;if(t)userSessions.delete(t);res.setHeader(String.fromCharCode(83,101,116,45,67,111,111,107,105,101),'linkbio_session=; HttpOnly; Path=/; SameSite=Lax; Max-Age=0');return res.json({success:true});}
    if(req.path==='/api/auth/register'&&req.method==='POST'){
      if(!adminClient)return res.status(503).json({success:false,message:'ระบบบัญชียังไม่ได้ตั้งค่า Service Role'});
      const email=String(req.body?.email||'').trim().toLowerCase(),password=String(req.body?.password||''),username=String(req.body?.username||'').trim().replace(/^@/,'');
      if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||password.length<8||!/^[a-zA-Z0-9._-]{2,40}$/.test(username))return res.status(400).json({success:false,message:'Email, Password หรือ Username ไม่ถูกต้อง'});
      const existing=await findUserByUsername(username);if(existing)return res.status(409).json({success:false,message:'Username นี้ถูกใช้งานแล้ว'});
      const created=await adminClient.auth.admin.createUser({email,password,email_confirm:true});if(created.error)throw created.error;const u=created.user;
      const base=clone(defaults);base.profile.username=username;base.profile.name=String(req.body?.name||username).slice(0,80);base.profile.displayName=base.profile.name;base.profile.email=email;
      for(const [section,value] of Object.entries(base)){if(['analytics','settings'].includes(section))continue;await saveSection(u.id,section,value);}
      await saveSection(u.id,'analytics',clone(defaults.analytics));await saveSection(u.id,'settings',clone(defaults.settings));
      const token=crypto.randomBytes(48).toString('hex');userSessions.set(token,{userId:u.id,exp:Date.now()+30*24*3600000});res.setHeader(String.fromCharCode(83,101,116,45,67,111,111,107,105,101),'linkbio_session='+token+'; HttpOnly; Path=/; SameSite=Lax; Max-Age=2592000');return res.json({success:true,user:{id:u.id,email,username}});
    }
    if(req.path==='/api/auth/login'&&req.method==='POST'){
      if(!adminClient)return res.status(503).json({success:false,message:'ระบบบัญชียังไม่ได้ตั้งค่า Service Role'});
      const email=String(req.body?.email||'').trim().toLowerCase(),password=String(req.body?.password||'');const auth=await adminClient.auth.signInWithPassword({email,password});if(auth.error) return res.status(401).json({success:false,message:'อีเมลหรือรหัสผ่านไม่ถูกต้อง'});const u=auth.data.user;
      const p=await sectionFor(u.id,'profile',clone(defaults.profile));const token=crypto.randomBytes(48).toString('hex');userSessions.set(token,{userId:u.id,exp:Date.now()+30*24*3600000});res.setHeader(String.fromCharCode(83,101,116,45,67,111,111,107,105,101),'linkbio_session='+token+'; HttpOnly; Path=/; SameSite=Lax; Max-Age=43200');return res.json({success:true,user:{id:u.id,email:u.email,username:p.username}});
    }
    if(req.path==='/api/auth/me'&&req.method==='GET'){const id=await resolveSession(req);if(!id)return res.json({success:true,loggedIn:false});const p=await sectionFor(id,'profile',{});return res.json({success:true,loggedIn:true,user:{id,username:p.username,email:p.email||''}})}
    if(req.path==='/api/auth/logout'&&req.method==='POST'){const t=cookies(req).linkbio_session;if(t)userSessions.delete(t);res.setHeader('Set-Cookie','linkbio_session=; HttpOnly; Path=/; SameSite=Lax; Max-Age=0');return res.json({success:true})}
    if(req.path==='/api/profile'&&req.method==='GET'){
      const id=await resolveUser(req,true);if(!id)return res.status(404).json({success:false,message:'ไม่พบโปรไฟล์'});const s=await sectionsFor(id);return res.json(publicPayload(s));
    }
    if(req.path==='/api/profile/stream'&&req.method==='GET')return next();
    if(req.path==='/api/analytics/view'&&req.method==='POST'){
      const id=await resolveUser(req,true);if(!id)return res.status(404).json({success:false,message:'ไม่พบโปรไฟล์'});const a=await sectionFor(id,'analytics',clone(defaults.analytics));const token=String(req.body?.sessionId||'').slice(0,120),seen=a.viewSessions||{},now=Date.now();if(!token)return res.status(400).json({success:false,message:'ต้องมี Session ID'});if(seen[token]&&now-Number(seen[token])<1800000)return res.json({success:true,counted:false,totalViews:a.profileViews||0});seen[token]=now;for(const k of Object.keys(seen))if(now-Number(seen[k])>86400000)delete seen[k];a.viewSessions=seen;a.profileViews=(a.profileViews||0)+1;a.viewsByDay=a.viewsByDay||{};const d=new Date().toISOString().slice(0,10);a.viewsByDay[d]=(a.viewsByDay[d]||0)+1;a.activity=[{type:'view',at:new Date().toISOString()}].concat(a.activity||[]).slice(0,100);a.lastUpdate=new Date().toISOString();await saveSection(id,'analytics',a);return res.json({success:true,counted:true,totalViews:a.profileViews});
    }
    const protectedSections={
      '/api/profile':'profile','/api/links':'links','/api/music':'music','/api/appearance':'appearance','/api/visualizer':'visualizer','/api/branding':'branding','/api/profile-card':'profileCard','/api/background':'background','/api/settings':'settings','/api/analytics':'analytics'
    };
    const isWrite=['POST','PUT','PATCH','DELETE'].includes(req.method);
    const protectedPath=Object.keys(protectedSections).find(p=>req.path===p||req.path.startsWith(p+'/'));
    if(protectedPath && isWrite){const own=await requireOwner(req,res);if(own.error)return res.status(401).json({success:false,message:own.error});const id=own.id;let section=protectedSections[protectedPath];let value=await sectionFor(id,section,clone(defaults[section]||{}));const pathId=decodeURIComponent(req.path.slice(protectedPath.length+1));
      if(req.path==='/api/profile'&&req.method==='PUT'){value={...value,...req.body,username:String(req.body?.username||value.username).replace(/^@/,'')};if(!/^[a-zA-Z0-9._-]{2,40}$/.test(value.username))return res.status(400).json({success:false,message:'Username ไม่ถูกต้อง'});value.verifiedIcon='✓';value.verifiedText='';value.verifiedPosition='inline';await saveSection(id,'profile',value);return res.json({success:true,message:'ปรับเรียบร้อยแล้ว',profile:value});}
      if((req.path==='/api/links'||req.path.startsWith('/api/links/'))){let arr=value||[];if(req.method==='POST'){const b=req.body||{};if(!clean(b.title,80)||!urlOK(b.url))return res.status(400).json({success:false,message:'ชื่อหรือ URL ไม่ถูกต้อง'});const n={...b,id:crypto.randomUUID(),title:clean(b.title,80),description:clean(b.description,180),url:b.url,icon:b.icon||siteIcon(b.url),iconKey:siteIcon(b.url),iconAuto:b.iconAuto!==false,enabled:b.enabled!==false,visible:b.visible!==false,openNewTab:b.openNewTab!==false,confirm:b.confirm===true,createdAt:new Date().toISOString()};arr=[...arr,n];await saveSection(id,'links',arr);return res.status(201).json({success:true,link:n,links:arr});}
        if(req.method==='PUT'&&pathId==='reorder'){arr=(req.body.links||[]).map((x,i)=>({...x,order:i}));await saveSection(id,'links',arr);return res.json({success:true,links:arr});}
        const idx=arr.findIndex(x=>x.id===pathId);if(idx<0)return res.status(404).json({success:false,message:'ไม่พบ Link'});if(req.method==='DELETE')arr.splice(idx,1);else {arr[idx]={...arr[idx],...req.body,id:arr[idx].id};if(arr[idx].iconAuto!==false){arr[idx].iconKey=siteIcon(arr[idx].url);arr[idx].icon=arr[idx].iconKey;}}await saveSection(id,'links',arr);return res.json({success:true,link:arr[idx],links:arr});
      }
      if(req.path==='/api/music'){let arr=value||[];if(req.method==='POST')return next();}
      if(req.path==='/api/music/youtube'&&req.method==='POST'){const idv=yt(req.body?.url);if(!idv)return res.status(400).json({success:false,message:'YouTube URL ไม่ถูกต้อง'});const n={id:crypto.randomUUID(),type:'youtube',youtubeId:idv,url:'https://www.youtube.com/watch?v='+idv,thumbnail:'https://i.ytimg.com/vi/'+idv+'/hqdefault.jpg',title:clean(req.body?.title,120)||'YouTube Track',artist:clean(req.body?.artist,80),enabled:true,order:(value||[]).length,createdAt:new Date().toISOString()};const arr=[...(value||[]),n];await saveSection(id,'music',arr);return res.status(201).json({success:true,track:n,music:arr});}
      if(req.path==='/api/music'&&req.method==='PUT'&&req.params.id==='reorder'){const arr=(req.body.music||[]).map((x,i)=>({...x,order:i}));await saveSection(id,'music',arr);return res.json({success:true,music:arr});}
      if(req.path==='/api/music/:id'){}
      if(['PUT','PATCH'].includes(req.method)){value={...value,...req.body};await saveSection(id,section,value);return res.json({success:true,message:'ปรับเรียบร้อยแล้ว',[section]:value});}
      if(req.method==='DELETE'){return res.status(405).json({success:false,message:'ลบรายการผ่าน endpoint เฉพาะ'});}
    }
    if(req.path==='/api/links/:id/click'&&req.method==='POST'){const id=await resolveUser(req,true);if(!id)return res.status(404).json({success:false,message:'ไม่พบโปรไฟล์'});const a=await sectionFor(id,'analytics',clone(defaults.analytics));a.clicksByLink=a.clicksByLink||{};a.clicksByDay=a.clicksByDay||{};a.clicksByLink[req.params.id]=(a.clicksByLink[req.params.id]||0)+1;const d=new Date().toISOString().slice(0,10);a.clicksByDay[d]=(a.clicksByDay[d]||0)+1;a.activity=[{type:'click',linkId:req.params.id,at:new Date().toISOString()}].concat(a.activity||[]).slice(0,100);a.lastUpdate=new Date().toISOString();await saveSection(id,'analytics',a);return res.json({success:true,clicks:a.clicksByLink[req.params.id]});}
    if(req.path==='/api/analytics/music-play'&&req.method==='POST'){const id=await resolveUser(req,true);if(!id)return res.status(404).json({success:false,message:'ไม่พบโปรไฟล์'});const a=await sectionFor(id,'analytics',clone(defaults.analytics));a.activity=[{type:'music-play',trackId:clean(req.body?.trackId,100),at:new Date().toISOString()}].concat(a.activity||[]).slice(0,100);a.lastUpdate=new Date().toISOString();await saveSection(id,'analytics',a);return res.json({success:true});}
    if(req.path==='/api/profile-card'&&req.method==='GET'){const id=await resolveUser(req,true);if(!id)return res.status(404).json({success:false,message:'ไม่พบโปรไฟล์'});return res.json({success:true,profileCard:await sectionFor(id,'profileCard',clone(defaults.profileCard))});}
    if(req.path==='/api/background'&&req.method==='GET'){const id=await resolveUser(req,true);if(!id)return res.status(404).json({success:false,message:'ไม่พบโปรไฟล์'});return res.json({success:true,background:await sectionFor(id,'background',clone(defaults.background))});}
    if(req.path==='/api/analytics'&&req.method==='GET'){const own=await requireOwner(req,res);if(own.error)return res.status(401).json({success:false,message:own.error});const a=await sectionFor(own.id,'analytics',clone(defaults.analytics)),l=await sectionFor(own.id,'links',[]),m=await sectionFor(own.id,'music',[]),clicks=a.clicksByLink||{};return res.json({success:true,totalProfileViews:a.profileViews||0,todayViews:(a.viewsByDay||{})[new Date().toISOString().slice(0,10)]||0,weeklyViews:Object.values(a.viewsByDay||{}).reduce((s,v)=>s+Number(v||0),0),monthlyViews:Object.values(a.viewsByDay||{}).reduce((s,v)=>s+Number(v||0),0),totalLinkClicks:Object.values(clicks).reduce((s,v)=>s+Number(v||0),0),todayClicks:(a.clicksByDay||{})[new Date().toISOString().slice(0,10)]||0,topLinks:l.map(x=>({...x,clicks:clicks[x.id]||0})).sort((x,y)=>y.clicks-x.clicks).slice(0,10),musicTracks:m.length,localMusic:m.filter(x=>x.type==='local').length,youtubeMusic:m.filter(x=>x.type==='youtube').length,_viewsByDay:a.viewsByDay||{},serverStatus:'online',apiStatus:'online',storageUsage:0,uploadCount:m.filter(x=>x.type==='local').length,recentActivity:(a.activity||[]).slice(0,20),lastUpdate:a.lastUpdate||null});}
    return next();
  }catch(e){console.error('Supabase middleware:',e);return res.status(500).json({success:false,message:e.message||'Supabase error'});}
}
app.use(handleSupabase);

const sessions=new Map();const ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||'adminsuguszx11';
function cookies(req){return Object.fromEntries(String(req.headers.cookie||'').split(';').map(x=>x.trim().split('=').map(decodeURIComponent)).filter(x=>x.length===2))}
function admin(req){const t=cookies(req).linkbio_admin,s=sessions.get(t);if(!s)return false;if(Date.now()>s.exp){sessions.delete(t);return false}return true}
function guard(req,res,next){if(!admin(req))return res.status(401).json({success:false,message:'กรุณาเข้าสู่ระบบ Admin'});next()}
app.get('/',(_q,r)=>r.sendFile(path.join(ROOT,'index.html')));app.get('/u/:username',(_q,r)=>r.sendFile(path.join(ROOT,'index.html')));app.get('/admin.html',(_q,r)=>r.sendFile(path.join(ROOT,'frontend','admin','index.html')));app.get('/terms.html',(_q,r)=>r.sendFile(path.join(ROOT,'terms.html')));app.get('/privacy.html',(_q,r)=>r.sendFile(path.join(ROOT,'privacy.html')));app.get('/register.html',(_q,r)=>r.sendFile(path.join(ROOT,'register.html')));
app.post('/api/admin/login',(req,res)=>{const p=String(req.body?.password||'');const a=Buffer.from(p),b=Buffer.from(ADMIN_PASSWORD);if(a.length!==b.length||!crypto.timingSafeEqual(a,b))return res.status(401).json({success:false,message:'รหัสผ่านไม่ถูกต้อง'});const token=crypto.randomBytes(48).toString('hex');sessions.set(token,{exp:Date.now()+12*3600000});res.setHeader('Set-Cookie',`linkbio_admin=${token}; HttpOnly; Path=/; SameSite=Lax; Max-Age=43200`);res.json({success:true})});
app.get('/api/admin/me',(q,r)=>r.json({success:true,loggedIn:admin(q)}));app.post('/api/admin/logout',(q,r)=>{const t=cookies(q).linkbio_admin;if(t)sessions.delete(t);r.setHeader('Set-Cookie','linkbio_admin=; HttpOnly; Path=/; SameSite=Lax; Max-Age=0');r.json({success:true})});
app.get('/api/profile',(req,res)=>{const s=publicSnapshot();res.set('Cache-Control','no-store');res.json({success:true,profile:{...s.profile,links:s.links,music:s.music,appearance:s.appearance,visualizer:s.visualizer,branding:s.branding,profileCard:s.profileCard,backgroundSettings:s.backgroundSettings}})});
app.get('/api/profile/stream',(req,res)=>{res.set({'Content-Type':'text/event-stream','Cache-Control':'no-cache, no-store, must-revalidate','Connection':'keep-alive','X-Accel-Buffering':'no'});res.flushHeaders?.();const client={write:chunk=>res.write(chunk)};publicClients.add(client);res.write(`event: ready\\ndata: ${JSON.stringify({type:'ready'})}\\n\\n`);const heartbeat=setInterval(()=>{try{res.write(': ping\\n\\n')}catch{}},15000);req.on('close',()=>{clearInterval(heartbeat);publicClients.delete(client);try{res.end()}catch{}})});
app.get('/api/profile-card',(q,r)=>r.json({success:true,profileCard:read('profileCard')}));
app.put('/api/profile-card',guard,(q,r)=>{try{const old=read('profileCard'),b={...old,...(q.body||{})};const error=validateProfileCard(b);if(error)return r.status(400).json({success:false,message:error});const x=patch('profileCard',b);r.json({success:true,message:'ปรับเรียบร้อยแล้ว',profileCard:x})}catch(e){console.error(e);r.status(500).json({success:false,message:'บันทึก Profile Card ไม่สำเร็จ'})}});
app.post('/api/analytics/view',(req,res)=>{const token=clean(req.body?.sessionId,120);if(!token)return res.status(400).json({success:false,message:'ต้องมี Session ID'});const a=read('analytics'),seen=a.viewSessions||{};const now=Date.now(),last=Number(seen[token]||0);if(last&&now-last<30*60*1000)return res.json({success:true,counted:false,totalViews:a.profileViews||0});seen[token]=now;for(const k of Object.keys(seen))if(now-Number(seen[k])>24*60*60*1000)delete seen[k];a.viewSessions=seen;a.profileViews=(a.profileViews||0)+1;a.viewsByDay=a.viewsByDay||{};a.viewsByDay[day()]=(a.viewsByDay[day()]||0)+1;a.activity=[{type:'view',at:new Date().toISOString()}].concat(a.activity||[]).slice(0,100);a.lastUpdate=new Date().toISOString();write('analytics',a);res.json({success:true,counted:true,totalViews:a.profileViews})});
app.put('/api/profile',guard,(req,res)=>{try{const b={...req.body,username:clean(req.body?.username,40),verifiedIcon:'✓',verifiedText:'',verifiedPosition:'inline',verifiedRadius:0,verifiedOpacity:1,verifiedTooltip:'Verified Profile'};const error=validateProfile(b);if(error)return res.status(400).json({success:false,message:error});const x=patch('profile',b),a=read('analytics');a.activity=[{type:'profile-update',at:new Date().toISOString()}].concat(a.activity||[]).slice(0,100);a.lastUpdate=new Date().toISOString();write('analytics',a);res.json({success:true,message:'ปรับเรียบร้อยแล้ว',profile:x})}catch(e){res.status(500).json({success:false,message:'บันทึกโปรไฟล์ไม่สำเร็จ'})}});
app.get('/api/links',(q,r)=>r.json({success:true,links:read('links')}));app.post('/api/links',guard,(req,res)=>{const b=req.body||{};if(!clean(b.title,80)||!urlOK(b.url))return res.status(400).json({success:false,message:'ชื่อหรือ URL ไม่ถูกต้อง'});const x=read('links');const n={id:crypto.randomUUID(),title:clean(b.title,80),description:clean(b.description,180),url:b.url,icon:clean(b.icon,80)||siteIcon(b.url),iconKey:siteIcon(b.url),iconAuto:b.iconAuto!==false,iconColor:b.iconColor||'',badge:clean(b.badge,20),enabled:b.enabled!==false,visible:b.visible!==false,openNewTab:b.openNewTab!==false,confirm:b.confirm===true,hover:clean(b.hover,20)||'none',style:clean(b.style,40)||'glass',startAt:b.startAt||'',endAt:b.endAt||'',timezone:b.timezone||'Asia/Bangkok',clicks:0,createdAt:new Date().toISOString()};x.push(n);write('links',x);res.status(201).json({success:true,link:n,links:x})});
app.put('/api/links/:id',guard,(req,res)=>{const x=read('links'),i=x.findIndex(z=>z.id===req.params.id);if(i<0)return res.status(404).json({success:false,message:'ไม่พบ Link'});x[i]={...x[i],...req.body,id:x[i].id};if(req.body.url&&!urlOK(req.body.url))return res.status(400).json({success:false,message:'URL ไม่ถูกต้อง'});if(x[i].iconAuto!==false){x[i].iconKey=siteIcon(x[i].url);x[i].icon=x[i].iconKey}write('links',x);res.json({success:true,link:x[i],links:x})});
app.delete('/api/links/:id',guard,(req,res)=>{const x=read('links').filter(z=>z.id!==req.params.id);write('links',x);res.json({success:true,links:x})});
app.put('/api/links/reorder',guard,(req,res)=>{if(!Array.isArray(req.body.links))return res.status(400).json({success:false,message:'links ต้องเป็น array'});write('links',req.body.links.map((z,i)=>({...z,order:i})));res.json({success:true,links:read('links')})});
app.post('/api/links/:id/click',(req,res)=>{const id=clean(req.params.id,100),x=read('analytics');x.clicksByLink=x.clicksByLink||{};x.clicksByDay=x.clicksByDay||{};x.clicksByLink[id]=(x.clicksByLink[id]||0)+1;x.clicksByDay[day()]=(x.clicksByDay[day()]||0)+1;x.activity=[{type:'click',linkId:id,at:new Date().toISOString()}].concat(x.activity||[]).slice(0,100);x.lastUpdate=new Date().toISOString();write('analytics',x);res.json({success:true,clicks:x.clicksByLink[id]})});
const safeBase=(s)=>path.basename(decodeURIComponent(String(s||'')));
const musicDir=path.join(UP,'music');
const musicUpload=multer({storage:multer.diskStorage({destination:musicDir,filename:(q,f,cb)=>{const e=path.extname(f.originalname).toLowerCase();const n=path.basename(f.originalname,e).replace(/[^a-zA-Z0-9._\-ก-๙ ]/g,'_').slice(0,80)||'track';cb(null,Date.now()+'-'+n+e)}}),limits:{fileSize:50*1024*1024},fileFilter:(q,f,cb)=>cb(null,/\.(mp3|wav|aac|m4a)$/i.test(f.originalname))});
const image=(dir,max,types)=>multer({storage:multer.diskStorage({destination:dir,filename:(q,f,cb)=>cb(null,Date.now()+'-'+crypto.randomBytes(5).toString('hex')+path.extname(f.originalname).toLowerCase())}),limits:{fileSize:max},fileFilter:(q,f,cb)=>cb(null,types.test(f.mimetype))});
const avatarUpload=image(path.join(UP,'avatars'),5*1024*1024,/^image\/(png|jpeg|webp|gif)$/i),coverUpload=image(path.join(UP,'covers'),8*1024*1024,/^image\/(png|jpeg|webp)$/i);
app.get('/api/background',(q,r)=>r.json({success:true,background:read('background')}));app.put('/api/background',guard,(q,r)=>{try{const b=q.body||{};if(!/^[a-z0-9-]{2,40}$/.test(String(b.preset||'')))return r.status(400).json({success:false,message:'Preset ไม่ถูกต้อง'});if(!num(b.intensity,0,1)||!num(b.speed,.1,4)||!num(b.opacity,0,1)||!['auto','low','medium','high'].includes(b.quality))return r.status(400).json({success:false,message:'ค่าพื้นหลังไม่ถูกต้อง'});if(typeof b.enabled!=='boolean'||typeof b.interaction!=='boolean')return r.status(400).json({success:false,message:'ค่า Toggle พื้นหลังไม่ถูกต้อง'});r.json({success:true,message:'ปรับเรียบร้อยแล้ว',background:patch('background',{...b,settings:typeof b.settings==='object'&&b.settings?b.settings:{}})})}catch(e){r.status(500).json({success:false,message:'บันทึกพื้นหลังไม่สำเร็จ'})}});
app.get('/api/appearance',(q,r)=>r.json({success:true,appearance:read('appearance')}));app.put('/api/appearance',guard,(q,r)=>{try{r.json({success:true,appearance:patch('appearance',q.body||{})})}catch(e){r.status(500).json({success:false,message:'บันทึก Appearance ไม่สำเร็จ'})}});
app.get('/api/visualizer',(q,r)=>r.json({success:true,visualizer:read('visualizer')}));app.put('/api/visualizer',guard,(q,r)=>{try{r.json({success:true,visualizer:patch('visualizer',q.body||{})})}catch(e){r.status(500).json({success:false,message:'บันทึก Visualizer ไม่สำเร็จ'})}});
app.get('/api/branding',(q,r)=>r.json({success:true,branding:read('branding')}));app.put('/api/branding',guard,(q,r)=>{try{r.json({success:true,branding:patch('branding',q.body||{})})}catch(e){r.status(500).json({success:false,message:'บันทึก Branding ไม่สำเร็จ'})}});
app.get('/api/settings',guard,(q,r)=>r.json({success:true,settings:read('settings')}));app.put('/api/settings',guard,(q,r)=>r.json({success:true,settings:patch('settings',q.body||{})}));
app.get('/api/analytics/views',guard,(q,r)=>{const a=read('analytics');r.json({success:true,total:a.profileViews||0,daily:a.viewsByDay||{}})});
app.get('/api/analytics/clicks',guard,(q,r)=>{const a=read('analytics');r.json({success:true,total:Object.values(a.clicksByLink||{}).reduce((s,v)=>s+Number(v||0),0),daily:a.clicksByDay||{},byLink:a.clicksByLink||{}})});
app.get('/api/analytics/links',guard,(q,r)=>{const a=read('analytics'),l=read('links');r.json({success:true,links:l.map(x=>({...x,clicks:Number((a.clicksByLink||{})[x.id]||0)})).sort((x,y)=>y.clicks-x.clicks)})});
app.get('/api/analytics/overview',guard,(q,r)=>{const a=read('analytics'),clicks=Object.values(a.clicksByLink||{}).reduce((s,v)=>s+Number(v||0),0);r.json({success:true,totalViews:a.profileViews||0,totalClicks:clicks,todayViews:(a.viewsByDay||{})[day()]||0,todayClicks:(a.clicksByDay||{})[day()]||0,viewsByDay:a.viewsByDay||{},clicksByDay:a.clicksByDay||{}})});
app.get('/api/analytics',guard,(q,r)=>{const a=read('analytics'),l=read('links'),m=read('music');const clicks=a.clicksByLink||{};r.json({success:true,totalProfileViews:a.profileViews||0,todayViews:(a.viewsByDay||{})[day()]||0,weeklyViews:Object.entries(a.viewsByDay||{}).filter(([d])=>Date.now()-Date.parse(d)<604800000).reduce((s,[,v])=>s+v,0),monthlyViews:Object.entries(a.viewsByDay||{}).filter(([d])=>d.slice(0,7)===day().slice(0,7)).reduce((s,[,v])=>s+v,0),totalLinkClicks:Object.values(clicks).reduce((s,v)=>s+Number(v||0),0),todayClicks:(a.clicksByDay||{})[day()]||0,topLinks:l.map(x=>({...x,clicks:clicks[x.id]||0})).sort((x,y)=>y.clicks-x.clicks).slice(0,10),musicTracks:m.length,localMusic:m.filter(x=>x.type==='local').length,youtubeMusic:m.filter(x=>x.type==='youtube').length,_viewsByDay:a.viewsByDay||{},serverStatus:'online',apiStatus:'online',storageUsage:fs.readdirSync(UP,{recursive:true}).reduce((s,n)=>{try{return s+fs.statSync(path.join(UP,n)).size}catch{return s}},0),uploadCount:m.filter(x=>x.type==='local').length,recentActivity:(a.activity||[]).slice(0,20),lastUpdate:a.lastUpdate||null})});
app.post('/api/analytics/music-play',(q,r)=>{const id=clean(q.body?.trackId,100);const a=read('analytics');a.activity=[{type:'music-play',trackId:id,at:new Date().toISOString()}].concat(a.activity||[]).slice(0,100);a.lastUpdate=new Date().toISOString();write('analytics',a);r.json({success:true})});
app.get('/api/music',(q,r)=>r.json({success:true,music:read('music')}));app.post('/api/music',guard,musicUpload.single('music'),(q,r)=>{if(!q.file)return r.status(400).json({success:false,message:'รองรับเฉพาะ MP3/WAV/AAC/M4A และไม่เกิน 50MB'});const x=read('music');const t={id:crypto.randomUUID(),type:'local',title:path.basename(q.file.originalname,path.extname(q.file.originalname)),artist:'',album:'',file:q.file.filename,url:'/uploads/music/'+encodeURIComponent(q.file.filename),enabled:true,order:x.length,createdAt:new Date().toISOString(),size:q.file.size};x.push(t);write('music',x);r.status(201).json({success:true,track:t,music:x})});
app.put('/api/music/:id',guard,(q,r)=>{const x=read('music'),i=x.findIndex(z=>z.id===q.params.id);if(i<0)return r.status(404).json({success:false,message:'ไม่พบเพลง'});x[i]={...x[i],...q.body,id:x[i].id};write('music',x);r.json({success:true,track:x[i]})});app.delete('/api/music/:id',guard,(q,r)=>{const x=read('music'),i=x.findIndex(z=>z.id===q.params.id);if(i<0)return r.status(404).json({success:false,message:'ไม่พบเพลง'});if(x[i].file){const f=path.join(musicDir,safeBase(x[i].file));if(fs.existsSync(f))fs.unlinkSync(f)}x.splice(i,1);write('music',x);r.json({success:true,music:x})});app.put('/api/music/reorder',guard,(q,r)=>{if(!Array.isArray(q.body.music))return r.status(400).json({success:false,message:'music ต้องเป็น array'});write('music',q.body.music.map((x,i)=>({...x,order:i})));r.json({success:true,music:read('music')})});
app.post('/api/music/youtube',guard,(q,r)=>{const id=yt(q.body?.url);if(!id)return r.status(400).json({success:false,message:'YouTube URL ไม่ถูกต้อง'});const x=read('music');const t={id:crypto.randomUUID(),type:'youtube',youtubeId:id,url:'https://www.youtube.com/watch?v='+id,thumbnail:'https://i.ytimg.com/vi/'+id+'/hqdefault.jpg',title:clean(q.body?.title,120)||'YouTube Track',artist:clean(q.body?.artist,80),enabled:true,order:x.length,createdAt:new Date().toISOString()};x.push(t);write('music',x);r.status(201).json({success:true,track:t,music:x})});
app.post('/api/admin/upload-avatar',guard,avatarUpload.single('avatar'),(q,r)=>{if(!q.file)return r.status(400).json({success:false,message:'ไฟล์ Avatar ไม่ถูกต้อง'});const p=patch('profile',{avatar:'/uploads/avatars/'+encodeURIComponent(q.file.filename)});r.json({success:true,profile:p})});app.post('/api/admin/upload-cover',guard,coverUpload.single('cover'),(q,r)=>{if(!q.file)return r.status(400).json({success:false,message:'ไฟล์ Cover ไม่ถูกต้อง'});const p=patch('profile',{cover:'/uploads/covers/'+encodeURIComponent(q.file.filename)});r.json({success:true,profile:p})});
app.get('/api/admin/status',guard,(q,r)=>r.json({success:true,status:'online',serverTime:new Date().toISOString()}));
const { registerSupport }=require('./support');
registerSupport(app,{isAdmin:admin});
app.use((err,q,r,n)=>{console.error(err);if(err instanceof multer.MulterError)return r.status(400).json({success:false,message:'อัปโหลดไม่สำเร็จ: '+err.message});r.status(500).json({success:false,message:'เกิดข้อผิดพลาดในเซิร์ฟเวอร์'})});app.use((q,r)=>r.status(404).json({success:false,message:'ไม่พบ endpoint'}));
app.listen(PORT,()=>console.log(`LinkBio running: http://localhost:${PORT}`));
