const crypto=require('crypto');
const {createClient}=require('@supabase/supabase-js');
function registerSupport(app,{isAdmin,resolveSupabaseUser}){
  const dbReady=!!(process.env.SUPABASE_URL&&process.env.SUPABASE_SERVICE_ROLE_KEY);
  const db=dbReady?createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}}):null;
  const sessions=new Map(),userClients=new Map(),adminClients=new Set();let adminPresenceUntil=0;
  const clean=(v,n)=>String(v??'').trim().slice(0,n);
  const cookie=(req,n)=>Object.fromEntries(String(req.headers.cookie||'').split(';').map(x=>x.trim().split('=').map(decodeURIComponent)).filter(x=>x.length===2))[n];
  const setCookie=(res,n,v,max=2592000)=>res.setHeader('Set-Cookie',`${n}=${encodeURIComponent(v)}; HttpOnly; Path=/; SameSite=Lax; Max-Age=${max}`);
  const fromDbTicket=x=>x&&({id:x.id,userId:x.user_id,email:x.email,displayName:x.display_name,photoUrl:x.photo_url,subject:x.subject,status:x.status,userUnread:x.user_unread,adminUnread:x.admin_unread,createdAt:x.created_at,updatedAt:x.updated_at});
  const fromDbMessage=x=>x&&({id:x.id,number:x.number,ticketId:x.ticket_id,sender:x.sender,senderId:x.sender_id,text:x.text,createdAt:x.created_at,readAt:x.read_at});
  async function ticketFor(id){if(!db)return null;const {data,error}=await db.from('support_tickets').select('*').eq('id',id).maybeSingle();if(error)throw error;return fromDbTicket(data)}
  async function messagesFor(id){if(!db)return [];const {data,error}=await db.from('support_messages').select('*').eq('ticket_id',id).order('number',{ascending:true});if(error)throw error;return (data||[]).map(fromDbMessage)}
  async function saveTicket(t){if(!db)return;const {error}=await db.from('support_tickets').upsert({id:t.id,user_id:t.userId,email:t.email||'',display_name:t.displayName||'',photo_url:t.photoUrl||'',subject:t.subject,status:t.status,user_unread:t.userUnread||0,admin_unread:t.adminUnread||0,created_at:t.createdAt,updated_at:t.updatedAt},{onConflict:'id'});if(error)throw error}
  async function addMessage(m){if(!db)return;const {error}=await db.from('support_messages').insert({id:m.id,ticket_id:m.ticketId,number:m.number,sender:m.sender,sender_id:m.senderId||'',text:m.text,created_at:m.createdAt,read_at:m.readAt});if(error)throw error}
  async function listTickets(uid){if(!db)return [];const q=db.from('support_tickets').select('*').order('updated_at',{ascending:false});const {data,error}=uid?q.eq('user_id',uid):await q;if(error)throw error;return (data||[]).map(fromDbTicket)}
  async function nextNumber(id){const ms=await messagesFor(id);return ms.reduce((n,m)=>Math.max(n,Number(m.number)||0),0)+1}
  async function publicTicket(t){return {...t,messageCount:(await messagesFor(t.id)).length}}
  async function markRead(id,side){if(!db)return;const t=await ticketFor(id);if(!t)return;const ms=await messagesFor(id),now=new Date().toISOString();for(const m of ms){if((side==='user'&&m.sender==='admin')||(side==='admin'&&m.sender==='user'))if(!m.readAt){await db.from('support_messages').update({read_at:now}).eq('id',m.id);}}
    if(side==='user')t.userUnread=0;else t.adminUnread=0;t.updatedAt=now;await saveTicket(t);}
  const emit=(uid,event,payload)=>{const d=`event: ${event}\ndata: ${JSON.stringify(payload)}\n\n`;for(const r of userClients.get(uid)||[])try{r.write(d)}catch{}};
  const emitAdmin=(event,payload)=>{const d=`event: ${event}\ndata: ${JSON.stringify(payload)}\n\n`;for(const r of adminClients)try{r.write(d)}catch{}};
  async function verifySupabaseToken(token){if(!resolveSupabaseUser||!token)throw Error('ไม่พบ LinkBio session');const u=await resolveSupabaseUser(token);if(!u)throw Error('LinkBio session หมดอายุหรือไม่ถูกต้อง');return {uid:u.id,email:u.email||'',displayName:u.user_metadata?.display_name||u.user_metadata?.full_name||'LinkBio User',photoUrl:u.user_metadata?.avatar_url||u.user_metadata?.picture||'',emailVerified:!!u.email_confirmed_at}}
  const userFromSession=req=>{const t=cookie(req,'linkbio_support'),s=t&&sessions.get(t);if(!s||s.exp<Date.now()){if(s)sessions.delete(t);return null}return s};
  const requireUser=(req,res)=>{const s=userFromSession(req);if(!s){res.status(401).json({success:false,message:'กรุณาเข้าสู่ระบบ LinkBio ก่อน'});return null}return s};
  async function aiReply(text){if(String(process.env.SUPPORT_AI_ENABLED||'true').toLowerCase()==='false')return null;const key=String(process.env.OPENAI_API_KEY||'').trim();if(key){try{const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${key}`},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-5.6-luna',input:`คุณคือ AI ผู้ช่วยของ DEKKHONGSHOP สำหรับ LinkBio ตอบภาษาไทยสุภาพ กระชับ ช่วยเรื่องลิงก์ โปรไฟล์ เว็บ และการใช้งานระบบ หากเป็นเรื่องบัญชี/ชำระเงิน/แก้ข้อมูลที่ต้องใช้สิทธิ์ ให้แจ้งว่าจะส่งต่อแอดมิน ห้ามอ้างว่าเป็นมนุษย์\nผู้ใช้: ${text}`,max_output_tokens:300})});const d=await r.json();const out=d.output_text||d.output?.flatMap(x=>x.content||[]).map(x=>x.text||'').join('').trim();if(r.ok&&out)return out}catch{}}
    const s=text.toLowerCase();if(/ลิ้ง|ลิงก์|link|bio/.test(s))return 'AI Assistant: ได้เลยครับ ถ้าต้องการทำลิงก์/LinkBio บอกได้เลยว่าอยากได้ชื่อ ลิงก์ และสไตล์ประมาณไหน เดี๋ยวผมช่วยเตรียมรายละเอียดให้แอดมินครับ';if(/เว็บ|website|เว็บไซต์/.test(s))return 'AI Assistant: ได้ครับ ถ้าต้องการทำเว็บไซต์ บอกประเภทเว็บ ฟีเจอร์หลัก และสไตล์ที่อยากได้ เดี๋ยวผมสรุปบรีฟให้แอดมินครับ';if(/ราคา|ค่าใช้|เท่าไหร่/.test(s))return 'AI Assistant: เรื่องราคาและใบเสนอราคาขอให้แอดมินตรวจสอบให้โดยตรงนะครับ ผมจะเก็บข้อความนี้ไว้ใน Ticket ให้ครับ';return 'AI Assistant: รับข้อความแล้วครับ ตอนนี้แอดมินอาจไม่อยู่ ระบบจะเก็บเรื่องไว้และแจ้งแอดมินเมื่อกลับมาออนไลน์ครับ';
  }
  app.post('/api/support/auth',async(req,res)=>{try{const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');const u=await verifySupabaseToken(token);const t=crypto.randomBytes(48).toString('hex');sessions.set(t,{...u,exp:Date.now()+30*24*3600000});setCookie(res,'linkbio_support',t);res.json({success:true,user:{...u,displayName:'@Dekkhong'}})}catch(e){res.status(401).json({success:false,message:e.message||'LinkBio login ไม่สำเร็จ'})}});
  app.get('/api/support/me',(req,res)=>{const s=userFromSession(req);res.json({success:true,loggedIn:!!s,user:s?{uid:s.uid,email:s.email,displayName:s.displayName,photoUrl:s.photoUrl}:null,adminOnline:Date.now()<adminPresenceUntil})});
  app.post('/api/support/logout',(req,res)=>{const t=cookie(req,'linkbio_support');if(t)sessions.delete(t);setCookie(res,'linkbio_support','',0);res.json({success:true})});
  app.get('/api/support/presence',(req,res)=>res.json({success:true,online:Date.now()<adminPresenceUntil}));
  app.get('/api/support/tickets',async(req,res)=>{try{const s=requireUser(req,res);if(!s)return;const ts=await listTickets(s.uid),out=[];for(const t of ts)out.push({...t,messageCount:(await messagesFor(t.id)).length});res.json({success:true,tickets:out,unread:ts.reduce((n,t)=>n+Number(t.userUnread||0),0),adminOnline:Date.now()<adminPresenceUntil})}catch(e){res.status(500).json({success:false,message:e.message})}});
  app.post('/api/support/tickets',async(req,res)=>{try{const s=requireUser(req,res);if(!s)return;const subject=clean(req.body?.subject,120)||'ติดต่อแอดมิน',first=clean(req.body?.message,2000);if(!first)return res.status(400).json({success:false,message:'กรุณาพิมพ์ข้อความก่อน'});const now=new Date().toISOString(),t={id:'ticket_'+crypto.randomBytes(6).toString('hex'),userId:s.uid,email:s.email,displayName:s.displayName,photoUrl:s.photoUrl,subject,status:'open',userUnread:0,adminUnread:1,createdAt:now,updatedAt:now};await saveTicket(t);const m={id:'message_'+crypto.randomBytes(7).toString('hex'),number:1,ticketId:t.id,sender:'user',senderId:s.uid,text:first,createdAt:now,readAt:null};await addMessage(m);emitAdmin('support:ticket-created',{ticket:await publicTicket(t),message:m});if(Date.now()>=adminPresenceUntil){const ai=await aiReply(first);if(ai){const at=new Date().toISOString(),am={id:'message_'+crypto.randomBytes(7).toString('hex'),number:2,ticketId:t.id,sender:'ai',senderId:'ai',text:ai,createdAt:at,readAt:null};await addMessage(am);t.userUnread=1;t.adminUnread=0;t.status='pending';t.updatedAt=at;await saveTicket(t);emit(s.uid,'support:message-created',{ticket:await publicTicket(t),message:am})}}res.status(201).json({success:true,ticket:await publicTicket(t),messages:await messagesFor(t.id)})}catch(e){res.status(500).json({success:false,message:e.message})}});
  app.get('/api/support/tickets/:id',async(req,res)=>{try{const s=requireUser(req,res);if(!s)return;const t=await ticketFor(req.params.id);if(!t||t.userId!==s.uid)return res.status(404).json({success:false,message:'ไม่พบห้องแชท'});t.userUnread=0;t.updatedAt=new Date().toISOString();await saveTicket(t);await markRead(t.id,'user');res.json({success:true,ticket:await publicTicket(t),messages:await messagesFor(t.id),adminOnline:Date.now()<adminPresenceUntil})}catch(e){res.status(500).json({success:false,message:e.message})}});
  app.post('/api/support/tickets/:id/messages',async(req,res)=>{try{const s=requireUser(req,res);if(!s)return;const t=await ticketFor(req.params.id);if(!t||t.userId!==s.uid)return res.status(404).json({success:false,message:'ไม่พบห้องแชท'});if(t.status==='closed')return res.status(409).json({success:false,message:'ห้องนี้ปิดแล้ว'});const text=clean(req.body?.message,2000);if(!text)return res.status(400).json({success:false,message:'ข้อความว่างเปล่า'});const now=new Date().toISOString(),m={id:'message_'+crypto.randomBytes(7).toString('hex'),number:await nextNumber(t.id),ticketId:t.id,sender:'user',senderId:s.uid,text,createdAt:now,readAt:null};await addMessage(m);t.adminUnread=(t.adminUnread||0)+1;t.userUnread=0;t.updatedAt=now;await saveTicket(t);emitAdmin('support:message-created',{ticket:await publicTicket(t),message:m});if(Date.now()>=adminPresenceUntil){const ai=await aiReply(text);if(ai){const at=new Date().toISOString(),am={id:'message_'+crypto.randomBytes(7).toString('hex'),number:await nextNumber(t.id),ticketId:t.id,sender:'ai',senderId:'ai',text:ai,createdAt:at,readAt:null};await addMessage(am);t.userUnread=1;t.adminUnread=0;t.status='pending';t.updatedAt=at;await saveTicket(t);emit(s.uid,'support:message-created',{ticket:await publicTicket(t),message:am})}}res.status(201).json({success:true,message:m,ticket:await publicTicket(t)})}catch(e){res.status(500).json({success:false,message:e.message})}});
  app.post('/api/support/tickets/:id/read',async(req,res)=>{try{const s=requireUser(req,res);if(!s)return;const t=await ticketFor(req.params.id);if(!t||t.userId!==s.uid)return res.status(404).json({success:false,message:'ไม่พบห้องแชท'});await markRead(t.id,'user');emitAdmin('support:message-read',{ticketId:t.id,by:'user'});res.json({success:true})}catch(e){res.status(500).json({success:false,message:e.message})}});
  app.post('/api/support/tickets/:id/close',async(req,res)=>{try{const s=requireUser(req,res);if(!s)return;const t=await ticketFor(req.params.id);if(!t||t.userId!==s.uid)return res.status(404).json({success:false,message:'ไม่พบห้องแชท'});t.status='closed';t.updatedAt=new Date().toISOString();await saveTicket(t);emitAdmin('support:ticket-updated',{ticket:await publicTicket(t)});res.json({success:true,ticket:await publicTicket(t)})}catch(e){res.status(500).json({success:false,message:e.message})}});
  app.get('/api/support/stream',(req,res)=>{const s=userFromSession(req);if(!s)return res.status(401).end();res.set({'Content-Type':'text/event-stream','Cache-Control':'no-cache, no-store','Connection':'keep-alive','X-Accel-Buffering':'no'});res.flushHeaders?.();const set=userClients.get(s.uid)||new Set();set.add(res);userClients.set(s.uid,set);res.write(`event: ready\ndata: ${JSON.stringify({ok:true})}\n\n`);const ping=setInterval(()=>{try{res.write(': ping\n\n')}catch{}},15000);req.on('close',()=>{clearInterval(ping);set.delete(res);if(!set.size)userClients.delete(s.uid)})});
  async function adminList(){return listTickets(null)}
  app.get('/api/support/admin/tickets',async(req,res)=>{try{if(!isAdmin(req))return res.status(401).json({success:false,message:'กรุณาเข้าสู่ระบบ Admin'});adminPresenceUntil=Date.now()+30000;const ts=await adminList();const out=[];for(const t of ts)out.push({...t,messageCount:(await messagesFor(t.id)).length});res.json({success:true,tickets:out,unread:ts.reduce((n,t)=>n+Number(t.adminUnread||0),0),online:true})}catch(e){res.status(500).json({success:false,message:e.message})}});
  app.post('/api/support/admin/presence',(req,res)=>{if(!isAdmin(req))return res.status(401).json({success:false,message:'กรุณาเข้าสู่ระบบ Admin'});adminPresenceUntil=Date.now()+30000;emitAdmin('support:presence',{online:true});for(const uid of userClients.keys())emit(uid,'support:presence',{online:true});res.json({success:true,online:true})});
  app.get('/api/support/admin/tickets/:id',async(req,res)=>{try{if(!isAdmin(req))return res.status(401).json({success:false,message:'กรุณาเข้าสู่ระบบ Admin'});adminPresenceUntil=Date.now()+30000;const t=await ticketFor(req.params.id);if(!t)return res.status(404).json({success:false,message:'ไม่พบ Ticket'});await markRead(t.id,'admin');res.json({success:true,ticket:await publicTicket(t),messages:await messagesFor(t.id)})}catch(e){res.status(500).json({success:false,message:e.message})}});
  app.post('/api/support/admin/tickets/:id/typing',async(req,res)=>{if(!isAdmin(req))return res.status(401).json({success:false});adminPresenceUntil=Date.now()+30000;const t=await ticketFor(req.params.id);if(!t)return res.status(404).json({success:false});emit(t.userId,'support:typing',{ticketId:t.id,typing:req.body?.typing!==false});res.json({success:true})});
  app.post('/api/support/admin/tickets/:id/reply',async(req,res)=>{try{if(!isAdmin(req))return res.status(401).json({success:false,message:'กรุณาเข้าสู่ระบบ Admin'});adminPresenceUntil=Date.now()+30000;const t=await ticketFor(req.params.id);if(!t)return res.status(404).json({success:false,message:'ไม่พบ Ticket'});if(t.status==='closed')return res.status(409).json({success:false,message:'Ticket นี้ปิดแล้ว'});const text=clean(req.body?.message,2000);if(!text)return res.status(400).json({success:false,message:'ข้อความว่างเปล่า'});const now=new Date().toISOString(),m={id:'message_'+crypto.randomBytes(7).toString('hex'),number:await nextNumber(t.id),ticketId:t.id,sender:'admin',senderId:'admin',text,createdAt:now,readAt:null};await addMessage(m);t.userUnread=(t.userUnread||0)+1;t.adminUnread=0;t.status='pending';t.updatedAt=now;await saveTicket(t);emit(t.userId,'support:message-created',{ticket:await publicTicket(t),message:m});emitAdmin('support:message-created',{ticket:await publicTicket(t),message:m});res.status(201).json({success:true,message:m,ticket:await publicTicket(t)})}catch(e){res.status(500).json({success:false,message:e.message})}});
  app.post('/api/support/admin/tickets/:id/status',async(req,res)=>{try{if(!isAdmin(req))return res.status(401).json({success:false,message:'กรุณาเข้าสู่ระบบ Admin'});adminPresenceUntil=Date.now()+30000;const t=await ticketFor(req.params.id);if(!t)return res.status(404).json({success:false,message:'ไม่พบ Ticket'});const status=['open','pending','closed'].includes(req.body?.status)?req.body.status:null;if(!status)return res.status(400).json({success:false,message:'สถานะไม่ถูกต้อง'});t.status=status;t.updatedAt=new Date().toISOString();if(status==='closed')t.userUnread=(t.userUnread||0)+1;await saveTicket(t);emit(t.userId,'support:ticket-updated',{ticket:await publicTicket(t)});emitAdmin('support:ticket-updated',{ticket:await publicTicket(t)});res.json({success:true,ticket:await publicTicket(t)})}catch(e){res.status(500).json({success:false,message:e.message})}});
  app.get('/api/support/admin/stream',(req,res)=>{if(!isAdmin(req))return res.status(401).end();adminPresenceUntil=Date.now()+30000;res.set({'Content-Type':'text/event-stream','Cache-Control':'no-cache, no-store','Connection':'keep-alive','X-Accel-Buffering':'no'});res.flushHeaders?.();adminClients.add(res);res.write(`event: ready\ndata: ${JSON.stringify({ok:true,online:true})}\n\n`);for(const uid of userClients.keys())emit(uid,'support:presence',{online:true});const ping=setInterval(()=>{try{adminPresenceUntil=Date.now()+30000;res.write(': ping\n\n')}catch{}},10000);req.on('close',()=>{clearInterval(ping);adminClients.delete(res);if(!adminClients.size){adminPresenceUntil=0;for(const uid of userClients.keys())emit(uid,'support:presence',{online:false})}try{res.end()}catch{}})});
}
module.exports={registerSupport};
