const fs=require('fs');
const path=require('path');
const crypto=require('crypto');

function registerSupport(app,{isAdmin}){
  const dir=path.join(__dirname,'database');
  const ticketsFile=path.join(dir,'support-tickets.json');
  const messagesFile=path.join(dir,'support-messages.json');
  fs.mkdirSync(dir,{recursive:true});
  if(!fs.existsSync(ticketsFile))fs.writeFileSync(ticketsFile,'[]');
  if(!fs.existsSync(messagesFile))fs.writeFileSync(messagesFile,'[]');
  const supportSessions=new Map();
  const userClients=new Map();
  const adminClients=new Set();
  const clean=(v,n)=>String(v??'').trim().slice(0,n);
  const read=p=>{try{return JSON.parse(fs.readFileSync(p,'utf8'))}catch{return []}};
  const write=(p,v)=>{const tmp=p+'.tmp';fs.writeFileSync(tmp,JSON.stringify(v,null,2));fs.renameSync(tmp,p)};
  const cookie=(req,n)=>Object.fromEntries(String(req.headers.cookie||'').split(';').map(x=>x.trim().split('=').map(decodeURIComponent)).filter(x=>x.length===2))[n];
  const setCookie=(res,n,v,max=2592000)=>res.setHeader('Set-Cookie',`${n}=${encodeURIComponent(v)}; HttpOnly; Path=/; SameSite=Lax; Max-Age=${max}`);
  const userFromSession=req=>{const t=cookie(req,'linkbio_support');const s=t&&supportSessions.get(t);if(!s||s.exp<Date.now()){if(s)supportSessions.delete(t);return null}return s};
  const emit=(userId,event,payload)=>{const data=`event: ${event}\ndata: ${JSON.stringify(payload)}\n\n`;for(const res of userClients.get(userId)||[])try{res.write(data)}catch{}}
  const emitAdmin=(event,payload)=>{const data=`event: ${event}\ndata: ${JSON.stringify(payload)}\n\n`;for(const res of adminClients)try{res.write(data)}catch{}};
  async function verifyFirebaseToken(token){
    const key=String(process.env.FIREBASE_API_KEY||'AIzaSyCJpSjW6Kb79eDqilEeTfo-gFL_sdzyjHY').trim();
    if(!token)throw Error('ไม่พบ Google session');
    const r=await fetch(`https://identitytoolkit.googleapis.com/v1/accounts:lookup?key=${encodeURIComponent(key)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({idToken:token})});
    const d=await r.json().catch(()=>({}));
    const u=d.users?.[0];
    if(!r.ok||!u||u.disabled)throw Error('Google session หมดอายุหรือไม่ถูกต้อง');
    return {uid:u.localId,email:u.email||'',displayName:u.displayName||'Google User',photoUrl:u.photoUrl||'',emailVerified:!!u.emailVerified};
  }
  const requireUser=(req,res)=>{const s=userFromSession(req);if(!s){res.status(401).json({success:false,message:'กรุณาเข้าสู่ระบบ Google ก่อน'});return null}return s};
  const ticketFor=(id)=>read(ticketsFile).find(x=>x.id===id);
  const messagesFor=id=>read(messagesFile).filter(x=>x.ticketId===id).sort((a,b)=>new Date(a.createdAt)-new Date(b.createdAt));
  const publicTicket=t=>({...t,messageCount:messagesFor(t.id).length});

  app.post('/api/support/auth',async(req,res)=>{try{const u=await verifyFirebaseToken(String(req.headers.authorization||'').replace(/^Bearer\s+/i,''));const token=crypto.randomBytes(48).toString('hex');supportSessions.set(token,{...u,exp:Date.now()+30*24*3600000});setCookie(res,'linkbio_support',token);res.json({success:true,user:u})}catch(e){res.status(401).json({success:false,message:e.message||'Google login ไม่สำเร็จ'})}});
  app.get('/api/support/me',(req,res)=>{const s=userFromSession(req);res.json({success:true,loggedIn:!!s,user:s?{uid:s.uid,email:s.email,displayName:s.displayName,photoUrl:s.photoUrl}:null})});
  app.post('/api/support/logout',(req,res)=>{const t=cookie(req,'linkbio_support');if(t)supportSessions.delete(t);setCookie(res,'linkbio_support','',0);res.json({success:true})});

  app.get('/api/support/tickets',(req,res)=>{const s=requireUser(req,res);if(!s)return;const items=read(ticketsFile).filter(x=>x.userId===s.uid).sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt));res.json({success:true,tickets:items.map(publicTicket),unread:items.reduce((n,t)=>n+Number(t.userUnread||0),0)})});
  app.post('/api/support/tickets',(req,res)=>{const s=requireUser(req,res);if(!s)return;const subject=clean(req.body?.subject,120)||'ติดต่อแอดมิน';const first=clean(req.body?.message,2000);if(!first)return res.status(400).json({success:false,message:'กรุณาพิมพ์ข้อความก่อน'});const now=new Date().toISOString();const t={id:'ticket_'+crypto.randomBytes(6).toString('hex'),userId:s.uid,email:s.email,displayName:s.displayName,photoUrl:s.photoUrl,subject,status:'open',userUnread:0,adminUnread:1,createdAt:now,updatedAt:now};const ts=read(ticketsFile);ts.push(t);write(ticketsFile,ts);const m={id:'message_'+crypto.randomBytes(7).toString('hex'),ticketId:t.id,sender:'user',senderId:s.uid,text:first,createdAt:now};const ms=read(messagesFile);ms.push(m);write(messagesFile,ms);emitAdmin('support:ticket-created',{ticket:publicTicket(t),message:m});res.status(201).json({success:true,ticket:publicTicket(t),messages:[m]})});
  app.get('/api/support/tickets/:id',(req,res)=>{const s=requireUser(req,res);if(!s)return;const t=ticketFor(req.params.id);if(!t||t.userId!==s.uid)return res.status(404).json({success:false,message:'ไม่พบห้องแชท'});t.userUnread=0;t.updatedAt=new Date().toISOString();const ts=read(ticketsFile),i=ts.findIndex(x=>x.id===t.id);if(i>=0)ts[i]=t;write(ticketsFile,ts);res.json({success:true,ticket:publicTicket(t),messages:messagesFor(t.id)})});
  app.post('/api/support/tickets/:id/messages',(req,res)=>{const s=requireUser(req,res);if(!s)return;const t=ticketFor(req.params.id);if(!t||t.userId!==s.uid)return res.status(404).json({success:false,message:'ไม่พบห้องแชท'});if(t.status==='closed')return res.status(409).json({success:false,message:'ห้องนี้ปิดแล้ว'});const text=clean(req.body?.message,2000);if(!text)return res.status(400).json({success:false,message:'ข้อความว่างเปล่า'});const now=new Date().toISOString();const m={id:'message_'+crypto.randomBytes(7).toString('hex'),ticketId:t.id,sender:'user',senderId:s.uid,text,createdAt:now};const ms=read(messagesFile);ms.push(m);write(messagesFile,ms);t.adminUnread=(t.adminUnread||0)+1;t.userUnread=0;t.updatedAt=now;const ts=read(ticketsFile),i=ts.findIndex(x=>x.id===t.id);ts[i]=t;write(ticketsFile,ts);emitAdmin('support:message-created',{ticket:publicTicket(t),message:m});res.status(201).json({success:true,message:m,ticket:publicTicket(t)})});
  app.post('/api/support/tickets/:id/read',(req,res)=>{const s=requireUser(req,res);if(!s)return;const t=ticketFor(req.params.id);if(!t||t.userId!==s.uid)return res.status(404).json({success:false,message:'ไม่พบห้องแชท'});t.userUnread=0;const ts=read(ticketsFile),i=ts.findIndex(x=>x.id===t.id);ts[i]=t;write(ticketsFile,ts);emitAdmin('support:message-read',{ticketId:t.id,by:'user'});res.json({success:true})});
  app.post('/api/support/tickets/:id/close',(req,res)=>{const s=requireUser(req,res);if(!s)return;const t=ticketFor(req.params.id);if(!t||t.userId!==s.uid)return res.status(404).json({success:false,message:'ไม่พบห้องแชท'});t.status='closed';t.updatedAt=new Date().toISOString();const ts=read(ticketsFile),i=ts.findIndex(x=>x.id===t.id);ts[i]=t;write(ticketsFile,ts);emitAdmin('support:ticket-updated',{ticket:publicTicket(t)});res.json({success:true,ticket:publicTicket(t)})});
  app.get('/api/support/stream',(req,res)=>{const s=userFromSession(req);if(!s)return res.status(401).end();res.set({'Content-Type':'text/event-stream','Cache-Control':'no-cache, no-store','Connection':'keep-alive','X-Accel-Buffering':'no'});res.flushHeaders?.();const set=userClients.get(s.uid)||new Set();set.add(res);userClients.set(s.uid,set);res.write(`event: ready\ndata: ${JSON.stringify({ok:true})}\n\n`);const ping=setInterval(()=>{try{res.write(': ping\n\n')}catch{}},15000);req.on('close',()=>{clearInterval(ping);set.delete(res);if(!set.size)userClients.delete(s.uid)})});
  app.get('/api/support/admin/tickets',(req,res)=>{if(!isAdmin(req))return res.status(401).json({success:false,message:'กรุณาเข้าสู่ระบบ Admin'});const ts=read(ticketsFile).sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt));res.json({success:true,tickets:ts.map(publicTicket),unread:ts.reduce((n,t)=>n+Number(t.adminUnread||0),0)})});
  app.get('/api/support/admin/tickets/:id',(req,res)=>{if(!isAdmin(req))return res.status(401).json({success:false,message:'กรุณาเข้าสู่ระบบ Admin'});const t=ticketFor(req.params.id);if(!t)return res.status(404).json({success:false,message:'ไม่พบ Ticket'});t.adminUnread=0;const ts=read(ticketsFile),i=ts.findIndex(x=>x.id===t.id);ts[i]=t;write(ticketsFile,ts);res.json({success:true,ticket:publicTicket(t),messages:messagesFor(t.id)})});
  app.post('/api/support/admin/tickets/:id/reply',(req,res)=>{if(!isAdmin(req))return res.status(401).json({success:false,message:'กรุณาเข้าสู่ระบบ Admin'});const t=ticketFor(req.params.id);if(!t)return res.status(404).json({success:false,message:'ไม่พบ Ticket'});if(t.status==='closed')return res.status(409).json({success:false,message:'Ticket นี้ปิดแล้ว'});const text=clean(req.body?.message,2000);if(!text)return res.status(400).json({success:false,message:'ข้อความว่างเปล่า'});const now=new Date().toISOString();const m={id:'message_'+crypto.randomBytes(7).toString('hex'),ticketId:t.id,sender:'admin',senderId:'admin',text,createdAt:now};const ms=read(messagesFile);ms.push(m);write(messagesFile,ms);t.userUnread=(t.userUnread||0)+1;t.adminUnread=0;t.status='pending';t.updatedAt=now;const ts=read(ticketsFile),i=ts.findIndex(x=>x.id===t.id);ts[i]=t;write(ticketsFile,ts);emit(t.userId,'support:message-created',{ticket:publicTicket(t),message:m});emitAdmin('support:message-created',{ticket:publicTicket(t),message:m});res.status(201).json({success:true,message:m,ticket:publicTicket(t)})});
  app.post('/api/support/admin/tickets/:id/status',(req,res)=>{if(!isAdmin(req))return res.status(401).json({success:false,message:'กรุณาเข้าสู่ระบบ Admin'});const t=ticketFor(req.params.id);if(!t)return res.status(404).json({success:false,message:'ไม่พบ Ticket'});const status=['open','pending','closed'].includes(req.body?.status)?req.body.status:null;if(!status)return res.status(400).json({success:false,message:'สถานะไม่ถูกต้อง'});t.status=status;t.updatedAt=new Date().toISOString();if(status==='closed')t.userUnread=(t.userUnread||0)+1;const ts=read(ticketsFile),i=ts.findIndex(x=>x.id===t.id);ts[i]=t;write(ticketsFile,ts);emit(t.userId,'support:ticket-updated',{ticket:publicTicket(t)});emitAdmin('support:ticket-updated',{ticket:publicTicket(t)});res.json({success:true,ticket:publicTicket(t)})});
  app.get('/api/support/admin/stream',(req,res)=>{if(!isAdmin(req))return res.status(401).end();res.set({'Content-Type':'text/event-stream','Cache-Control':'no-cache, no-store','Connection':'keep-alive','X-Accel-Buffering':'no'});res.flushHeaders?.();adminClients.add(res);res.write(`event: ready\ndata: ${JSON.stringify({ok:true})}\n\n`);const ping=setInterval(()=>{try{res.write(': ping\n\n')}catch{}},15000);req.on('close',()=>{clearInterval(ping);adminClients.delete(res);try{res.end()}catch{}})});
}
module.exports={registerSupport};
