from pathlib import Path
root=Path(r'C:\Users\icetv\Downloads\LinkBio-MusicVisualizer-Final\LinkBio\frontend')
files=[root/'admin'/'index.html',root/'admin'/'admin.js',root/'profile'/'index.html',root/'profile'/'app.js',root/'music-player'/'player.js']
mp={
'LINKBIO STUDIO':'LINKBIO สตูดิโอ','STUDIO ADMIN':'ผู้ดูแลระบบ','WORKSPACE':'เมนูหลัก','Server Online':'เซิร์ฟเวอร์ออนไลน์','Public Profile':'หน้าโปรไฟล์สาธารณะ','Preview':'ดูตัวอย่าง','Dashboard':'แดชบอร์ด','Profile':'โปรไฟล์','Links':'ลิงก์','Music':'เพลง','Appearance':'การแสดงผล','Visualizer':'วิชวลไลเซอร์','Branding':'แบรนด์','Analytics':'สถิติ','Settings':'ตั้งค่า','SAVE':'บันทึก','RESET':'รีเซ็ต','PREVIEW':'ดูตัวอย่าง','Instant':'ทันที','Live':'เรียลไทม์','JSON Database':'ฐานข้อมูล JSON','Quick Actions':'เมนูด่วน','Active Links':'ลิงก์ที่ใช้งาน','Music Tracks':'เพลงทั้งหมด','Server Status':'สถานะเซิร์ฟเวอร์','CREATOR CONTROL':'ศูนย์ควบคุมครีเอเตอร์','Profile Identity':'ข้อมูลโปรไฟล์','Profile Assets':'รูปภาพโปรไฟล์','Typography & Colors':'ตัวอักษรและสี','Verified Badge':'ป้ายยืนยันตัวตน','Enable Verified Badge':'เปิดใช้ป้ายยืนยันตัวตน','Live Preview':'ตัวอย่างแบบเรียลไทม์','Profile Management':'จัดการโปรไฟล์','Link Library':'รายการลิงก์','Add Link':'เพิ่มลิงก์','Edit':'แก้ไข','Duplicate':'ทำสำเนา','Delete':'ลบ','Enabled':'เปิดใช้งาน','Disabled':'ปิดใช้งาน','Local Audio':'เสียงจากเครื่อง','YouTube Music':'เพลงจาก YouTube','Song Name':'ชื่อเพลง','Artist':'ศิลปิน','YouTube URL':'ลิงก์ YouTube','Add YouTube Track':'เพิ่มเพลง YouTube','YouTube Track Added':'เพิ่มเพลง YouTube แล้ว','Video ID':'รหัสวิดีโอ','Mode Rules':'กติกาการทำงาน','Visualizer Engine':'ระบบวิชวลไลเซอร์','Mode':'โหมด','Sensitivity':'ความไว','Smoothing':'ความนุ่มนวล','Bar Count':'จำนวนแท่ง','Bar Width':'ความกว้างแท่ง','Bar Gap':'ระยะห่างแท่ง','Height':'ความสูง','Glow':'แสงเรือง','Speed':'ความเร็ว','Rotation':'การหมุน','Mirror':'สะท้อน','Responsive':'ปรับตามหน้าจอ','Background Color':'สีพื้นหลัง','Gradient 1':'สีไล่ระดับ 1','Gradient 2':'สีไล่ระดับ 2','Gradient Angle':'มุมไล่ระดับ','Image / GIF URL':'ลิงก์รูปภาพ / GIF','Video URL':'ลิงก์วิดีโอ','Blur':'เบลอ','Effect Intensity':'ความเข้มเอฟเฟกต์','Particle Count':'จำนวนอนุภาค','Particle Speed':'ความเร็วอนุภาค','Performance Mode':'โหมดประสิทธิภาพ','Effects':'เอฟเฟกต์','System':'ระบบ','Views':'การเข้าชม','Daily':'รายวัน','Top Links':'ลิงก์ยอดนิยม','Clicks':'คลิก','Storage':'พื้นที่จัดเก็บ','Total Views':'การเข้าชมทั้งหมด','Today Views':'การเข้าชมวันนี้','Total Clicks':'คลิกทั้งหมด','Today Clicks':'คลิกวันนี้','Cancel':'ยกเลิก','Title':'ชื่อ','Description':'คำอธิบาย','Icon':'ไอคอน','Hover Effect':'เอฟเฟกต์เมื่อชี้','Schedule Start':'เริ่มแสดง','Schedule End':'สิ้นสุดการแสดง','Open New Tab':'เปิดแท็บใหม่','Confirm Before Open':'ยืนยันก่อนเปิด','Custom Text':'ข้อความกำหนดเอง','Custom Icon':'ไอคอนกำหนดเอง','Position':'ตำแหน่ง','Color':'สี','Border':'ขอบ','NOW PLAYING':'กำลังเล่น','Made with':'สร้างด้วย','Track':'เพลง','Unknown Artist':'ไม่ทราบชื่อศิลปิน','Online':'ออนไลน์','Offline':'ออฟไลน์','Away':'ไม่อยู่','Working':'กำลังทำงาน','Gaming':'กำลังเล่นเกม','Busy':'ไม่ว่าง','Local':'ในเครื่อง'}
for f in files:
 s=f.read_text(encoding='utf-8'); old=s
 for a,b in mp.items(): s=s.replace(a,b)
 if s!=old: f.write_text(s,encoding='utf-8'); print('updated',f)
