const supaClient=window.supabaseClient;
let supportUser=null,activeTicket=null,pollTimer=null;
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function getSupabase(){
 if(supaClient)return supaClient;
 const cfg=await fetch('/api/config/public',{cache:'no-store'}).then(r=>r.json());
 if(!cfg.supabaseUrl||!cfg.supabasePublishableKey)throw Error('ระบบบัญชียังไม่ได้ตั้งค่า Supabase');
 const lib=window.supabase||await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm');
 const create=lib.createClient||lib.default?.createClient;
 return create(cfg.supabaseUrl,cfg.supabasePublishableKey);
}
async function api(url,opt={}){
 const s=await getSupabase().catch(()=>null),session=s?await s.auth.getSession():null;
 const token=session?.data?.session?.access_token;
 const headers={'Content-Type':'application/json',...(opt.headers||{})};
 if(token&&!headers.Authorization)headers.Authorization='Bearer '+token;
 const r=await fetch(url,{credentials:'same-origin',cache:'no-store',...opt,headers});
 const d=await r.json().catch(()=>({}));
 if(!r.ok)throw Error(d.message||('HTTP '+r.status));
 return d;
}
function notify(){try{const A=new AudioContext(),o=A.createOscillator(),g=A.createGain();o.frequency.value=740;g.gain.setValueAtTime(.0001,A.currentTime);g.gain.exponentialRampToValueAtTime(.12,A.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,A.currentTime+.18);o.connect(g).connect(A.destination);o.start();o.stop(A.currentTime+.2)}catch{}}
function setPresence(v){const el=$('#supportPresence');if(!el)return;el.innerHTML=v?'<i class="online-dot"></i> <b>ออนไลน์</b>':'<i class="offline-dot"></i> <b>ออฟไลน์</b>'}
function mount(){
 if($('#supportRoot'))return;
 const root=document.createElement('div');root.id='supportRoot';
 root.innerHTML='<button id="supportFab" class="support-fab"><span class="support-fab-icon">✦</span><span>ติดต่อแอดมิน</span><i id="supportUnread"></i></button><div id="supportOverlay" class="support-overlay" aria-hidden="true"><section class="support-panel"><div id="supportLogin" class="support-login"><div class="support-login-orb">✦</div><span class="support-kicker">DEKKHONGSHOP SUPPORT</span><h2>ศูนย์ช่วยเหลือ</h2><p>เข้าสู่ระบบ LinkBio เพื่อส่งข้อความและติดตามการตอบกลับ</p><button id="supportGoogle" class="support-google"><b>G</b> ดำเนินการต่อด้วย Google</button><small id="supportError"></small></div><div id="supportChat" class="support-chat hidden"><header class="support-head"><div class="support-agent"><div class="support-agent-avatar">DS</div><div><strong>DEKKHONGSHOP</strong><span id="supportPresence"><i></i> <b>ออฟไลน์</b></span></div></div><button id="supportClose" class="support-close">×</button></header><div class="support-body"><aside class="support-tickets"><div class="support-tickets-head"><strong>การติดต่อของฉัน</strong><button id="supportNew">＋</button></div><div id="supportTicketList"></div></aside><main class="support-conversation"><div id="supportEmpty" class="support-empty"><div>✦</div><strong>ติดต่อแอดมิน</strong><span>เลือกห้องเดิมหรือสร้าง Ticket ใหม่</span><button id="supportStart">เริ่มแชทใหม่</button></div><div id="supportThread" class="hidden"><div class="support-thread-head"><div><strong id="supportSubject">—</strong><span id="supportStatus">—</span></div><button id="supportCloseTicket">ปิด Ticket</button></div><div id="supportQuick" class="support-quick"><button data-q="ต้องการให้ช่วยทำลิงก์หรือเว็บไซต์">ทำลิงก์ / เว็บไซต์</button><button data-q="อยากให้ทำลิงก์ให้หน่อย">ทำลิงก์</button><button data-q="อยากให้ทำเว็บไซต์ให้หน่อย">ทำเว็บไซต์</button><button data-q="สอบถามบริการ">สอบถามบริการ</button></div><div id="supportMessages" class="support-messages"></div><form id="supportForm" class="support-composer"><textarea id="supportMessage" maxlength="2000" rows="1" placeholder="พิมพ์ข้อความถึงแอดมิน..."></textarea><button type="submit">➤</button></form></div></main></div><footer class="support-footer"><span>สร้างด้วย <b>DEKKHONGSHOP</b> ©</span></footer></div></section></div></div>';
 document.body.appendChild(root);bind();
}
async function ensureSession(){try{const d=await api('/api/support/me');if(d.loggedIn){supportUser=d.user;setPresence(d.adminOnline);return true}}catch{}return false}
async function googleLogin(){const e=$('#supportError');e.textContent='';try{const s=await getSupabase();const r=await s.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.href}});if(r.error)throw r.error}catch(x){e.textContent=x.message||'เข้าสู่ระบบไม่สำเร็จ'}}
async function openChat(){const o=$('#supportOverlay');o.classList.add('is-open');o.setAttribute('aria-hidden','false');document.body.classList.add('support-lock');$('#supportLogin').classList.toggle('hidden',!!supportUser);$('#supportChat').classList.toggle('hidden',!supportUser);if(supportUser){await loadTickets();startPolling()}}
function closeChat(){const o=$('#supportOverlay');o.classList.remove('is-open');o.setAttribute('aria-hidden','true');document.body.classList.remove('support-lock')}
async function loadTickets(){const d=await api('/api/support/tickets');setPresence(d.adminOnline);const u=$('#supportUnread');u.textContent=d.unread>99?'99+':(d.unread||'');u.style.display=d.unread?'grid':'none';const list=$('#supportTicketList');list.innerHTML=(d.tickets||[]).map(t=>'<button class="support-ticket '+(activeTicket?.id===t.id?'active':'')+'" data-ticket="'+esc(t.id)+'"><span>'+esc(t.subject)+'</span><small>'+esc(t.status||'open')+' · '+(t.messageCount||0)+' ข้อความ</small></button>').join('')||'<div class="support-no-tickets">ยังไม่มี Ticket</div>';list.querySelectorAll('[data-ticket]').forEach(b=>b.onclick=()=>openTicket(b.dataset.ticket))}
async function openTicket(id){const d=await api('/api/support/tickets/'+encodeURIComponent(id));activeTicket=d.ticket;$('#supportEmpty').classList.add('hidden');$('#supportThread').classList.remove('hidden');$('#supportSubject').textContent=d.ticket.subject;$('#supportStatus').textContent=d.ticket.status==='closed'?'ปิดแล้ว':d.ticket.status==='pending'?'แอดมินตอบแล้ว':'รอแอดมิน';$('#supportCloseTicket').style.display=d.ticket.status==='closed'?'none':'inline-flex';renderMessages(d.messages||[]);await loadTickets()}
function renderMessages(ms){const box=$('#supportMessages');if(!box)return;box.innerHTML=(ms||[]).map(m=>{const who=m.sender==='user'?'user':'admin';const ai=m.sender==='ai'?'<b class="ai-label">AI</b> ':'';const read=m.sender==='user'?(m.readAt?'<span class="read-ok">อ่านแล้ว</span>':'<span>ยังไม่ได้อ่าน</span>'):'';const text=esc(m.text).replace(/\n/g,'<br>');const time=new Date(m.createdAt).toLocaleString('th-TH',{hour:'2-digit',minute:'2-digit'});return '<div class="support-message '+who+'"><div class="support-number">#'+(m.number||'')+'</div><div class="support-bubble">'+ai+text+'</div><time>'+time+(read?' · '+read:'')+'</time></div>'}).join('');box.scrollTop=box.scrollHeight}
async function newTicket(prefill=''){const subject=prompt('หัวข้อ Ticket','ต้องการให้ช่วยทำลิงก์หรือเว็บไซต์');if(!subject)return;const message=prompt('รายละเอียด',prefill||'');if(!message)return;try{const d=await api('/api/support/tickets',{method:'POST',body:JSON.stringify({subject:subject.trim(),message:message.trim()})});activeTicket=d.ticket;await openTicket(activeTicket.id)}catch(e){alert(e.message)}}
async function sendMessage(e){e.preventDefault();if(!activeTicket||activeTicket.status==='closed')return;const input=$('#supportMessage'),message=input.value.trim();if(!message)return;input.value='';try{const d=await api('/api/support/tickets/'+encodeURIComponent(activeTicket.id)+'/messages',{method:'POST',body:JSON.stringify({message})});activeTicket=d.ticket;renderMessages(await getMessages(activeTicket.id));await loadTickets();notify()}catch(err){input.value=message;alert(err.message)}}
async function getMessages(id){const d=await api('/api/support/tickets/'+encodeURIComponent(id));return d.messages||[]}
async function closeTicket(){if(!activeTicket||!confirm('ปิด Ticket นี้ใช่ไหม?'))return;const d=await api('/api/support/tickets/'+encodeURIComponent(activeTicket.id)+'/close',{method:'POST'});activeTicket=d.ticket;renderMessages(await getMessages(activeTicket.id));await loadTickets()}
function startPolling(){clearInterval(pollTimer);pollTimer=setInterval(async()=>{if(document.visibilityState==='hidden'||!supportUser)return;try{await refreshPresence();if(activeTicket){const d=await api('/api/support/tickets/'+encodeURIComponent(activeTicket.id));activeTicket=d.ticket;renderMessages(d.messages||[])}await loadTickets()}catch{}},8000)}
async function refreshPresence(){try{const d=await api('/api/support/presence');setPresence(d.online)}catch{setPresence(false)}}
function bind(){$('#supportFab').onclick=async()=>{if(await ensureSession())openChat();else{$('#supportOverlay').classList.add('is-open');$('#supportOverlay').setAttribute('aria-hidden','false');document.body.classList.add('support-lock')}};window.openLinkBioSupport=()=>$('#supportFab')?.click();document.addEventListener('linkbio:open-support',()=>window.openLinkBioSupport?.());$('#supportGoogle').onclick=googleLogin;$('#supportClose').onclick=closeChat;$('#supportNew').onclick=()=>newTicket();$('#supportStart').onclick=()=>newTicket();$('#supportCloseTicket').onclick=closeTicket;$('#supportForm').onsubmit=sendMessage;document.querySelectorAll('#supportQuick button').forEach(b=>b.onclick=()=>{$('#supportMessage').value=b.dataset.q;$('#supportMessage').focus()});$('#supportMessage').addEventListener('input',e=>{e.target.style.height='auto';e.target.style.height=Math.min(120,e.target.scrollHeight)+'px'})}
mount();getSupabase().then(async s=>{const {data}=await s.auth.getSession();if(data.session){supportUser=(await api('/api/support/auth',{method:'POST'})).user;openChat()}s.auth.onAuthStateChange(async(_event,session)=>{if(session){try{supportUser=(await api('/api/support/auth',{method:'POST'})).user;openChat()}catch{}}else supportUser=null})}).catch(()=>{});
