(()=>{
const $=id=>document.getElementById(id),audio=$('audio'),play=$('play'),progress=$('progress'),volume=$('volume'),playlist=$('playlist'),ytHost=$('yt-player');let tracks=[],i=0,shuffle=false,repeat='all',ytReady=false;
const fmt=s=>`${Math.floor((s||0)/60)}:${String(Math.floor((s||0)%60)).padStart(2,'0')}`;const current=()=>tracks[i];
function loadYTAPI(){if(window.YT?.Player){ytReady=true;return Promise.resolve()}return new Promise(resolve=>{const old=window.onYouTubeIframeAPIReady;window.onYouTubeIframeAPIReady=()=>{ytReady=true;old?.();resolve()};if(!document.querySelector('script[src*="youtube.com/iframe_api"]')){const s=document.createElement('script');s.src='https://www.youtube.com/iframe_api';document.head.appendChild(s)}})}
async function loadYT(id,autoplay){await loadYTAPI();ytHost.innerHTML='';window.ytPlayer=new YT.Player(ytHost,{width:'200',height:'200',videoId:id,playerVars:{playsinline:1,controls:0,rel:0,modestbranding:1},events:{onReady:e=>{e.target.setVolume(+volume.value*100);if(autoplay)e.target.playVideo();},onStateChange:e=>{if(e.data===YT.PlayerState.PLAYING){play.textContent='❚❚';document.body.classList.add('youtube-playing');window.LinkBioVisualizer?.setMode('none');reportPlay();}if(e.data===YT.PlayerState.PAUSED)play.textContent='▶';if(e.data===YT.PlayerState.ENDED)ended()}}})}
function reportPlay(){const t=current();if(t?.id)fetch('/api/analytics/music-play',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({trackId:t.id})}).catch(()=>{})}
function setTrack(n,autoplay=false){if(!tracks.length)return;i=(n+tracks.length)%tracks.length;const t=current();document.body.classList.toggle('youtube-mode',t.type==='youtube');$('title').textContent=t.title||t.name||'ยังไม่มีเพลง';$('artist').textContent=t.artist||'เพลงจาก LinkBio';$('cover').src=t.thumbnail||t.cover||'https://placehold.co/180x180/png?text=Music';document.querySelectorAll('.song').forEach((e,k)=>e.classList.toggle('active',k===i));if(t.type==='youtube'){audio.pause();audio.removeAttribute('src');ytHost.style.display='block';loadYT(t.youtubeId,autoplay);window.LinkBioVisualizer?.setMode('none')}else{window.ytPlayer?.pauseVideo();ytHost.innerHTML='';ytHost.style.display='none';audio.src=t.url;window.LinkBioVisualizer?.setMode('bars');if(autoplay)audio.play().catch(()=>{play.textContent='▶'})}}
function render(){playlist.innerHTML='';tracks.forEach((t,n)=>{const e=document.createElement('div');e.className='song';e.innerHTML=`<span>${n+1}. ${String(t.title||t.name||'Track').replace(/[<>]/g,'')}</span><small>${t.type==='youtube'?'YouTube':'เพลงจากเครื่อง'}</small>`;e.onclick=()=>setTrack(n,true);playlist.appendChild(e)})}
function ended(){if(repeat==='one')return setTrack(i,true);if(repeat==='off'&&i===tracks.length-1)return;setTrack(shuffle?Math.floor(Math.random()*tracks.length):i+1,true)}
play.onclick=()=>{const t=current();if(t?.type==='youtube'){if(window.ytPlayer?.getPlayerState?.()===1)window.ytPlayer.pauseVideo();else window.ytPlayer?.playVideo();return}audio.paused?audio.play().catch(()=>{}):audio.pause()};
audio.onplay=()=>{play.textContent='❚❚';reportPlay();window.LinkBioAudio?.start()};audio.onpause=()=>play.textContent='▶';audio.onloadedmetadata=()=>{$('duration').textContent=fmt(audio.duration)};audio.ontimeupdate=()=>{$('current').textContent=fmt(audio.currentTime);progress.value=audio.duration?audio.currentTime/audio.duration*100:0};progress.oninput=()=>{const t=current();if(t?.type==='youtube')window.ytPlayer?.seekTo((progress.value/100)*(window.ytPlayer.getDuration()||0),true);else if(audio.duration)audio.currentTime=progress.value/100*audio.duration};
volume.oninput=()=>{audio.volume=+volume.value;window.ytPlayer?.setVolume(+volume.value*100)};audio.volume=.8;$('next').onclick=()=>setTrack(shuffle?Math.floor(Math.random()*tracks.length):i+1,true);$('prev').onclick=()=>setTrack(i-1,true);$('shuffle').onclick=()=>{shuffle=!shuffle;$('shuffle').style.opacity=shuffle?'1':'.55'};$('loop').onclick=()=>{repeat=repeat==='off'?'all':repeat==='all'?'one':'off';$('loop').title='Repeat: '+repeat};audio.onended=ended;
setInterval(()=>{const t=current();if(t?.type==='youtube'&&window.ytPlayer?.getCurrentTime){const d=window.ytPlayer.getDuration()||0,c=window.ytPlayer.getCurrentTime()||0;$('current').textContent=fmt(c);$('duration').textContent=fmt(d);progress.value=d?c/d*100:0}},300);
window.LinkBioPlayer={setTracks(x){tracks=Array.isArray(x)?x.filter(t=>t.enabled!==false):[];render();if(tracks[0])setTrack(0,false)}};
})();
