(()=>{
'use strict';
const c=document.getElementById('bgCanvas');if(!c)return;const x=c.getContext('2d');
const names=['floating-particles','neon-particles','star-field','shooting-stars','meteor-rain','snow','rain','heavy-rain','light-rain','fireflies','aurora','aurora-waves','galaxy','space-dust','cosmic-energy','nebula','plasma','electric','lightning','energy-waves','ripple','water-ripple','smoke','fog','mist','lava','fire','embers','digital-rain','matrix','cyber-grid','neon-grid','laser-lines','scanlines','hologram','rgb-wave','rgb-glow','gradient-flow','mesh-gradient','liquid-gradient','color-waves','light-beams','floating-orbs','glowing-bubbles','dna-motion','sound-waves','equalizer-background','circuit-flow','cyber-particles','neon-universe'];
let cfg={enabled:true,preset:'floating-particles',intensity:.7,speed:1,opacity:.9,quality:'auto',performanceMode:false,interaction:true,settings:{}},w=0,h=0,dpr=1,t=0,last=performance.now(),frames=0,fps=60,density=1,raf=0,mouse={x:-1,y:-1},seed=[];
const rnd=(a=0,b=1)=>a+Math.random()*(b-a),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function resize(){w=innerWidth;h=innerHeight;dpr=Math.min(devicePixelRatio||1,cfg.quality==='low'?1:cfg.quality==='medium'?1.5:2);c.width=w*dpr;c.height=h*dpr;c.style.width=w+'px';c.style.height=h+'px';x.setTransform(dpr,0,0,dpr,0,0);makeSeed()}
function count(base){return Math.floor(base*density*(cfg.performanceMode?0.55:1)*(innerWidth<600?.65:1))}
function makeSeed(){const n=count(150);seed=Array.from({length:n},()=>({x:rnd(0,w),y:rnd(0,h),vx:rnd(-.4,.4),vy:rnd(-.4,.4),r:rnd(1,4),a:rnd(.2,1),z:rnd(.2,1),phase:rnd(0,Math.PI*2)}))}
function clear(){x.clearRect(0,0,w,h)}
function dot(p,r=p.r,a=p.a){x.globalAlpha=a*(cfg.opacity??.9);x.beginPath();x.arc(p.x,p.y,r,0,Math.PI*2);x.fill()}
function particles(kind){const s=cfg.settings||{};x.fillStyle=s.color||'#a855f7';seed.forEach((p,i)=>{p.x+=p.vx*cfg.speed;p.y+=p.vy*cfg.speed;if(kind==='neon')p.x+=Math.sin(t*.001+p.phase)*.35;if(kind==='firefly')p.y-=Math.sin(t*.001+p.phase)*.5;if(p.x<0)p.x=w;if(p.x>w)p.x=0;if(p.y<0)p.y=h;if(p.y>h)p.y=0;dot(p,p.r*(s.size||1),p.a);if(kind==='neon'){x.shadowBlur=14;x.shadowColor=s.color||'#a855f7'}else x.shadowBlur=0;if((s.lines??kind==='neon')&&i<seed.length-1){const q=seed[i+1],d=Math.hypot(p.x-q.x,p.y-q.y);if(d<110){x.globalAlpha=.12;x.beginPath();x.moveTo(p.x,p.y);x.lineTo(q.x,q.y);x.stroke()}}});x.shadowBlur=0}
function rain(mult,angle){x.strokeStyle=cfg.settings.color||'#60a5fa';x.lineWidth=1;x.globalAlpha=cfg.opacity;seed.forEach(p=>{p.y+=cfg.speed*(3+mult*4);p.x+=Math.sin(angle)*cfg.speed*2;if(p.y>h+30){p.y=-30;p.x=rnd(0,w)}x.beginPath();x.moveTo(p.x,p.y);x.lineTo(p.x-Math.sin(angle)*mult*10,p.y+mult*10);x.stroke()})}
function stars(depth=1){x.fillStyle='#fff';seed.forEach(p=>{p.y+=cfg.speed*(.05+.3*p.z);if(p.y>h)p.y=0;const z=.5+p.z*depth;dot(p,p.r*z,.2+p.a*.5)})}
function waves(type){x.lineWidth=2;x.globalAlpha=cfg.opacity;for(let k=0;k<5;k++){x.beginPath();for(let px=0;px<=w;px+=10){const yy=h*(.25+k*.14)+Math.sin(px*.008+t*.001*(cfg.speed+k*.15)+k)*35*(cfg.intensity+.2);if(!px)x.moveTo(px,yy);else x.lineTo(px,yy)}x.strokeStyle=type==='rgb'?`hsl(${(t*.05+k*70)%360} 90% 65%)`:cfg.settings.color||'#a855f7';x.stroke()}}
function gradient(type){const g=x.createLinearGradient(0,0,w,h);if(type==='rgb'){g.addColorStop(0,`hsl(${t*.04%360} 90% 55%)`);g.addColorStop(.5,`hsl(${(t*.04+130)%360} 90% 55%)`);g.addColorStop(1,`hsl(${(t*.04+260)%360} 90% 55%)`)}else{g.addColorStop(0,cfg.settings.color1||'#7c3aed');g.addColorStop(.5,cfg.settings.color2||'#06b6d4');g.addColorStop(1,cfg.settings.color3||'#ec4899')}x.globalAlpha=cfg.opacity*.35;x.fillStyle=g;x.fillRect(0,0,w,h)}
function drawPreset(){const p=cfg.preset;if(p==='floating-particles')particles('normal');
else if(p==='neon-particles')particles('neon');else if(p==='star-field')stars(1);else if(p==='shooting-stars'){stars(.7);rain(.35,-.8)}else if(p==='meteor-rain')rain(1,-.65);else if(p==='snow')rain(.22,.25);else if(p==='rain')rain(.55,0);else if(p==='heavy-rain')rain(1.2,0);else if(p==='light-rain')rain(.32,0);else if(p==='fireflies')particles('firefly');else if(p==='aurora'||p==='aurora-waves')waves('aurora');else if(p==='galaxy'){x.save();x.translate(w/2,h/2);x.rotate(t*.00008*cfg.speed);stars(.9);x.restore()}else if(p==='space-dust')particles('normal');else if(p==='cosmic-energy'){waves('rgb');particles('neon')}else if(p==='nebula'){gradient('normal');waves('aurora')}else if(p==='plasma'){gradient('rgb');waves('rgb')}else if(p==='electric'){waves('rgb');rain(.4,Math.sin(t*.002)*1.2)}else if(p==='lightning'){rain(1.3,-.15);x.strokeStyle='#fff';x.lineWidth=2;for(let k=0;k<3;k++){x.beginPath();x.moveTo(rnd(0,w),0);for(let j=0;j<7;j++)x.lineTo(rnd(0,w),rnd(0,h));x.stroke()}}else if(p==='energy-waves')waves('rgb');else if(p==='ripple'){const s=cfg.settings||{};x.strokeStyle=s.color||'#a855f7';for(let r=10;r<Math.max(w,h);r+=55){const rr=(r+t*.06*cfg.speed)%Math.max(w,h);x.globalAlpha=.12;x.beginPath();x.arc(w/2,h/2,rr,0,Math.PI*2);x.stroke()}}else if(p==='water-ripple'){x.strokeStyle='#38bdf8';for(let r=15;r<Math.max(w,h);r+=42){const rr=(r+t*.04*cfg.speed)%Math.max(w,h);x.globalAlpha=.16;x.beginPath();x.ellipse(w/2,h/2,rr,rr*.38,0,0,Math.PI*2);x.stroke()}}else if(p==='smoke'||p==='fog'||p==='mist'){gradient('normal');particles('normal')}else if(p==='lava'){x.fillStyle='#ff4d00';seed.forEach(q=>{q.y-=cfg.speed*(.3+q.z);if(q.y<0)q.y=h;dot(q,q.r*2,q.a*.7)})}else if(p==='fire'){x.fillStyle='#ff7a00';seed.forEach(q=>{q.y-=cfg.speed*(1+q.z);q.x+=Math.sin(t*.004+q.phase)*.7;if(q.y<0)q.y=h;dot(q,q.r*2,q.a)})}else if(p==='embers'){x.fillStyle='#ff5a36';particles('neon')}else if(p==='digital-rain')rain(.8,0);else if(p==='matrix'){x.fillStyle='#39ff88';x.font='12px monospace';seed.forEach(q=>{q.y+=cfg.speed*(1+q.z)*2;if(q.y>h)q.y=-20;x.globalAlpha=.3+q.a*.5;x.fillText(String.fromCharCode(0x30a0+Math.floor(q.x)%80),q.x,q.y)})}else if(p==='cyber-grid'||p==='neon-grid'){x.strokeStyle=cfg.settings.color||'#7c3aed';x.globalAlpha=.18;const gap=cfg.settings.gridSize||48,off=(t*.03*cfg.speed)%gap;for(let xx=-gap;xx<w+gap;xx+=gap){x.beginPath();x.moveTo(xx+off,0);x.lineTo(w/2+(xx-w/2)*.35,h);x.stroke()}for(let yy=0;yy<h;yy+=gap){x.beginPath();x.moveTo(0,yy+off);x.lineTo(w,yy+off);x.stroke()}}else if(p==='laser-lines'){x.strokeStyle='#ec4899';for(let k=0;k<7;k++){const yy=(k*h/7+t*.12*cfg.speed)%h;x.beginPath();x.moveTo(0,yy);x.lineTo(w,yy+Math.sin(t*.002+k)*80);x.stroke()}}else if(p==='scanlines'){x.fillStyle='#fff';for(let yy=(t*.08*cfg.speed)%8;yy<h;yy+=8){x.globalAlpha=.045;x.fillRect(0,yy,w,1)}}
else if(p==='hologram'){x.strokeStyle='#22d3ee';x.globalAlpha=.16;for(let yy=0;yy<h;yy+=5){const dy=Math.sin(yy*.04+t*.003)*8;x.beginPath();x.moveTo(0,yy+dy);x.lineTo(w,yy-dy);x.stroke()}}else if(p==='rgb-wave')waves('rgb');else if(p==='rgb-glow'){gradient('rgb');particles('neon')}else if(p==='gradient-flow'){gradient('normal');waves('aurora')}else if(p==='mesh-gradient'){gradient('rgb');for(let k=0;k<8;k++){x.globalAlpha=.08;x.fillStyle=`hsl(${(t*.03+k*45)%360} 90% 60%)`;x.beginPath();x.arc(w*(.15+k*.11),h*(.2+.15*Math.sin(t*.001+k)),180,0,7);x.fill()}}else if(p==='liquid-gradient'){gradient('rgb');for(let k=0;k<6;k++){x.globalAlpha=.08;x.fillStyle=`hsl(${(k*60+t*.05)%360} 90% 60%)`;x.beginPath();x.ellipse(w*(.15+k*.15),h/2+Math.sin(t*.001+k)*100,170,80,0,0,7);x.fill()}}else if(p==='color-waves')waves('rgb');else if(p==='light-beams'){x.globalAlpha=.08;for(let k=0;k<8;k++){x.fillStyle=`hsl(${(k*45+t*.02)%360} 90% 60%)`;x.beginPath();x.moveTo(w/2,0);x.lineTo(k*w/8,h);x.lineTo((k+1)*w/8,h);x.closePath();x.fill()}}else if(p==='floating-orbs'){x.fillStyle='#8b5cf6';seed.slice(0,35).forEach(q=>{q.x+=Math.sin(t*.001+q.phase)*.5;q.y+=Math.cos(t*.0012+q.phase)*.4;dot(q,10+q.r*4,.18)})}else if(p==='glowing-bubbles'){x.fillStyle='#38bdf8';seed.slice(0,55).forEach(q=>{q.y-=cfg.speed*(.2+q.z);if(q.y<-20)q.y=h+20;x.globalAlpha=.16;q.r=3+Math.sin(t*.001+q.phase)*2;x.beginPath();x.arc(q.x,q.y,5+q.r,0,7);x.stroke()})}else if(p==='dna-motion'){x.strokeStyle='#a855f7';for(let k=0;k<2;k++){x.beginPath();for(let yy=0;yy<h;yy+=8){const xx=w/2+Math.sin(yy*.025+t*.002)*90+(k?0:0);k?x.lineTo(xx+Math.PI*0+70,yy):x.lineTo(xx,yy)}x.stroke()}for(let yy=0;yy<h;yy+=28){const xx=w/2+Math.sin(yy*.025+t*.002)*90;x.beginPath();x.moveTo(xx,yy);x.lineTo(xx+70,yy);x.stroke()}}else if(p==='sound-waves'){waves('rgb')}else if(p==='equalizer-background'){x.fillStyle='#a855f7';const n=40;for(let k=0;k<n;k++){const bh=20+Math.abs(Math.sin(t*.004+k*.7))*h*.18;x.globalAlpha=.12;x.fillRect(k*w/n,h-bh,w/n-2,bh)}}else if(p==='circuit-flow'){x.strokeStyle='#22d3ee';x.lineWidth=1;for(let k=0;k<16;k++){const yy=(k*73+t*.04*cfg.speed)%h;x.beginPath();x.moveTo(0,yy);x.lineTo(w*.25,yy);x.lineTo(w*.35,yy+40);x.lineTo(w*.7,yy+40);x.stroke()}}else if(p==='cyber-particles')particles('neon');else if(p==='neon-universe'){stars(1.4);particles('neon');waves('rgb')}}
function frame(now){const dt=now-last;last=now;fps=1000/Math.max(1,dt);frames++;if(frames%60===0){if(fps<32)density=clamp(density*.85,.35,1);else if(fps>52)density=clamp(density+.05,.35,1)}t+=dt;clear();if(cfg.enabled!==false){x.save();if(cfg.interaction&&mouse.x>=0){x.translate((mouse.x-w/2)*.006,(mouse.y-h/2)*.006)}drawPreset();x.restore()}x.globalAlpha=1;raf=requestAnimationFrame(frame)}
function setConfig(v){cfg={...cfg,...v,settings:{...(cfg.settings||{}),...(v?.settings||{})}};if(!names.includes(cfg.preset))cfg.preset='floating-particles';density=1;makeSeed();}
addEventListener('resize',resize);addEventListener('pointermove',e=>{mouse.x=e.clientX;mouse.y=e.clientY});addEventListener('pointerleave',()=>{mouse.x=mouse.y=-1});
window.LinkBioBackground={setConfig,getPresets:()=>names.slice(),getFPS:()=>fps};resize();raf=requestAnimationFrame(frame);
})();
