(()=>{
'use strict';
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const checks=[
 ['Admin Session','/api/admin/me'],['Supabase Config','/api/config/public'],['Profile API','/api/profile'],['Analytics API','/api/analytics'],['Links API','/api/links'],['Music API','/api/music'],['Profile Card','/api/profile-card'],['Background API','/api/background'],['Appearance API','/api/appearance'],['Visualizer API','/api/visualizer'],['Branding API','/api/branding'],['Settings API','/api/settings'],['GIF Stickers','/api/gif-stickers'],['GIPHY Proxy','/api/giphy/search?q=sparkle&limit=1'],['Support API','/api/support'],['Public Profile','/profile']
];
let samples=[];try{samples=JSON.parse(localStorage.getItem('lb_api_candles')||'[]')}catch{}
let lastResults=[],running=false,round=0,totalRounds=6,timer=null;
async function probe(name,url){const t=performance.now();try{const r=await fetch(url,{credentials:'same-origin',cache:'no-store'});const ms=Math.round(performance.now()-t);return{name,url,ok:r.ok,status:r.status,ms};}catch(e){return{name,url,ok:false,status:0,ms:Math.round(performance.now()-t),error:e.message}}}
function chart(){const a=samples.slice(-30);if(!a.length)return '<div class="api-empty">เริ่ม Deep Scan เพื่อสร้างแท่งเทียน...</div>';const w=1100,h=300,p=24,max=Math.max(100,...a.map(x=>x.high)),min=0,span=max-min,bw=Math.max(6,Math.min(24,(w-p*2)/a.length-5)),y=v=>h-p-(v/span)*(h-p*2);return `<svg class="api-candles" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none">${a.map((x,i)=>{const cx=p+(i+.5)*(w-p*2)/a.length,yo=y(x.open),yc=y(x.close),yh=y(x.high),yl=y(x.low),up=x.close<=x.open,top=Math.min(yo,yc),bh=Math.max(3,Math.abs(yc-yo));return `<g class="api-candle ${up?'up':'down'}"><line x1="${cx}" x2="${cx}" y1="${yh}" y2="${yl}"/><rect x="${cx-bw/2}" y="${top}" width="${bw}" height="${bh}" rx="2"><title>O ${x.open}ms H ${x.high}ms L ${x.low}ms C ${x.close}ms</title></rect></g>`}).join('')}</svg><div class="api-axis"><span>0 ms</span><span>${Math.round(max/2)} ms</span><span>${Math.round(max)} ms</span></div>`}
function render(){const r=lastResults,g=r.filter(x=>x.ok).length,t=r.length,a=t?Math.round(r.reduce((s,x)=>s+x.ms,0)/t):0;return `<section class="api-monitor"><div class="api-monitor-head"><div><div class="eyebrow">SYSTEM HEALTH</div><h2>API Monitor</h2><p>Deep Scan 60 วินาที • ${round}/${totalRounds} รอบ • ตรวจซ้ำทุก 10 วินาที</p></div><div class="api-monitor-actions"><span class="api-health ${g===t&&t?'good':'bad'}"><i></i>${g}/${t} API ปกติ</span><button id="apiCheckNow" class="btn btn-primary">⟳ ตรวจสอบใหม่</button></div></div><div class="api-progress"><div style="width:${Math.min(100,round/totalRounds*100)}%"></div></div><div class="api-summary"><div><b>${g}/${t}</b><span>Healthy</span></div><div><b>${a} ms</b><span>Average latency</span></div><div><b>${samples.length}</b><span>Candles</span></div><div><b>${running?'กำลังตรวจ':'ตรวจเสร็จ'}</b><span>Scan state</span></div></div><div class="api-panel panel"><div class="panel-title"><h3>Latency Candlestick / OHLC</h3><span>ทุก 10 วินาที • เก็บ 30 แท่งล่าสุด</span></div><div class="api-chart-box">${chart()}</div></div><div class="api-panel panel"><div class="panel-title"><h3>Service Status</h3><span>HTTP + latency + error</span></div><div class="api-service-grid">${r.map(x=>`<div class="api-service ${x.ok?'ok':'fail'}"><i></i><div><strong>${esc(x.name)}</strong><small>${x.status||'ERR'} • ${x.ms} ms${x.error?' • '+esc(x.error):''}</small></div><b>${x.ok?'ONLINE':'DOWN'}</b></div>`).join('')}</div></div></section>`}
async function scan(){if(running)return;running=true;round=0;lastResults=[];renderRoot();for(let i=1;i<=totalRounds;i++){round=i;const results=await Promise.all(checks.map(x=>probe(x[0],x[1])));lastResults=results;const v=results.map(x=>x.ms).filter(Number.isFinite);if(v.length){samples.push({open:v[0],high:Math.max(...v),low:Math.min(...v),close:v[v.length-1],at:Date.now()});samples=samples.slice(-30);localStorage.setItem('lb_api_candles',JSON.stringify(samples))}renderRoot();if(i<totalRounds)await new Promise(r=>setTimeout(r,10000));}running=false;renderRoot();clearInterval(timer);timer=setInterval(scan,30000)}
function renderRoot(){const root=$('#apiMonitorRoot');if(root){root.innerHTML=render();$('#apiCheckNow')?.addEventListener('click',()=>{clearInterval(timer);scan()})}}
window.openApiMonitor=()=>{const app=$('#app');if(!app)return;app.innerHTML='<div id="apiMonitorRoot"></div>';renderRoot();scan()};
})();
