(()=>{
'use strict';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const checks=[
 ['Server / Express','/api/admin/status'],['Supabase / Profile','/api/profile'],['Analytics API','/api/analytics'],['Links API','/api/links'],['Music API','/api/music'],['Profile Card','/api/profile-card'],['Background API','/api/background'],['Appearance API','/api/appearance'],['Visualizer API','/api/visualizer'],['Branding API','/api/branding'],['Settings API','/api/settings'],['Support API','/api/support'],['GIPHY Proxy','/api/giphy/search?q=ping&limit=1'],['Public Profile','/profile'],['Public Config','/api/config/public']
];
let samples=[];
try{samples=JSON.parse(localStorage.getItem('lb_api_candles')||'[]')}catch{}
const api=async(url)=>{const t=performance.now();try{const r=await fetch(url,{credentials:'same-origin',cache:'no-store'});const ms=Math.round(performance.now()-t);return {ok:r.ok||[401,403,405].includes(r.status),status:r.status,ms}}catch(e){return {ok:false,status:0,ms:Math.round(performance.now()-t),error:e.message}}};
function candleChart(){const a=samples.slice(-30);if(!a.length)return '<div class="api-empty">กำลังเก็บข้อมูล latency...</div>';const max=Math.max(1,...a.map(x=>x.high));const min=Math.min(0,...a.map(x=>x.low));const span=Math.max(1,max-min),w=920,h=250,p=18,bw=Math.max(8,Math.min(22,(w-2*p)/a.length-5));const y=v=>h-p-((v-min)/span)*(h-p*2);return `<svg class="api-candles" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" aria-label="API latency candlestick chart">${a.map((x,i)=>{const cx=p+(i+.5)*(w-2*p)/a.length,yo=y(x.open),yc=y(x.close),yh=y(x.high),yl=y(x.low),top=Math.min(yo,yc),height=Math.max(2,Math.abs(yc-yo)),up=x.close<=x.open;return `<g class="api-candle ${up?'up':'down'}"><line x1="${cx}" x2="${cx}" y1="${yh}" y2="${yl}"/><rect x="${cx-bw/2}" y="${top}" width="${bw}" height="${height}" rx="2"><title>Open ${x.open}ms • High ${x.high}ms • Low ${x.low}ms • Close ${x.close}ms</title></rect></g>`}).join('')}</svg><div class="api-chart-axis"><span>${Math.round(max)} ms</span><span>${Math.round((max+min)/2)} ms</span><span>${Math.round(min)} ms</span></div>`}
function renderShell(results,loading=false){const good=results.filter(x=>x.ok).length,total=results.length,avg=total?Math.round(results.reduce((s,x)=>s+x.ms,0)/total):0;return `<section class="api-monitor"><div class="api-monitor-head"><div><div class="eyebrow">SYSTEM HEALTH</div><h2>API Monitor</h2><p>ตรวจทุก API ในหน้าเดียว พร้อม latency แบบแท่งเทียน OHLC</p></div><div class="api-monitor-actions"><span class="api-health ${good===total&&total?'good':'bad'}"><i></i>${loading?'กำลังตรวจ...':good+'/'+total+' API ปกติ'}</span><button id="apiCheckNow" class="btn btn-primary">⟳ ตรวจสอบตอนนี้</button></div></div><div class="api-summary"><div><b>${good}/${total}</b><span>Healthy</span></div><div><b>${avg} ms</b><span>Average latency</span></div><div><b>10s</b><span>Auto refresh</span></div><div><b>${samples.length}</b><span>Candles</span></div></div><div class="api-panel panel"><div class="panel-title"><h3>Latency Candlestick</h3><span>Green = close ดีขึ้น • Red = latency สูงขึ้น</span></div><div class="api-chart-box">${candleChart()}</div></div><div class="api-panel panel"><div class="panel-title"><h3>Service Status</h3><span>HTTP + response time</span></div><div class="api-service-grid">${results.map(x=>`<div class="api-service ${x.ok?'ok':'fail'}"><i></i><div><strong>${esc(x.name)}</strong><small>${x.status||'ERR'} • ${x.ms} ms${x.error?' • '+esc(x.error):''}</small></div><b>${x.ok?'ONLINE':'DOWN'}</b></div>`).join('')}</div></div></section>`}
async function run(){const root=$('#apiMonitorRoot');if(!root)return;root.innerHTML=renderShell([],true);const results=await Promise.all(checks.map(async([name,url])=>({name,url,...await api(url)})));const vals=results.map(x=>x.ms).filter(Number.isFinite);if(vals.length){const open=vals[0],close=vals[vals.length-1];samples.push({open,high:Math.max(...vals),low:Math.min(...vals),close,at:Date.now()});samples=samples.slice(-30);localStorage.setItem('lb_api_candles',JSON.stringify(samples))}root.innerHTML=renderShell(results);$('#apiCheckNow')?.addEventListener('click',run)}
window.openApiMonitor=()=>{const root=$('#app');if(!root)return;root.innerHTML='<div id="apiMonitorRoot"></div>';run()};
})();
