(()=>{'use strict';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const api=async(u,o={})=>{const r=await fetch(u,{credentials:'same-origin',cache:'no-store',...o,headers:{'Content-Type':'application/json',...(o.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||`HTTP ${r.status}`);return d};
let tickets=[],active=null,stream=null,adminPresence=null,typingStop=null;
function navButton(){if(!$('#nav'))return;let b=$('#supportNav')||$('#nav [data-section="support"]');if(!b){b=document.createElement('button');b.className='nav-item';b.dataset.section='support';b.innerHTML='<i class="nav-icon">◉</i><span>ติดต่อแอดมิน</span>';$('#nav').appendChild(b)}b.id='supportNav';if(!$('#supportAdminBadge')){const badge=document.createElement('em');badge.id='supportAdminBadge';b.appendChild(badge)}b.onclick=openSupport}
async function presence(){try{await api('/api/support/admin/presence',{method:'POST'})}catch{}}
async function loadTickets(){const d=await api('/api/support/admin/tickets');tickets=d.tickets||[];const badge=$('#supportAdminBadge');if(badge){badge.textContent=d.unread>99?'99+':(d.unread||'');badge.style.display=d.unread?'grid':'none'}renderList();}
function renderList(){const list=$('#supportAdminList');if(!list)return;$('#supportTicketCount').textContent=tickets.length;list.innerHTML=tickets.length?tickets.map(t=>`<button class="support-admin-ticket ${active?.id===t.id?'active':''}" data-id="${esc(t.id)}"><div><strong>#${esc(t.messageCount||0)} · ${esc(t.subject)}</strong><span>${esc(t.displayName||'Google User')} · ${esc(t.email||'')}</span></div><small class="${t.status}">${t.status==='closed'?'ปิดแล้ว':t.status==='pending'?'รอผู้ใช้':'รอแอดมิน'}</small></button>`).join(''):'<div class="support-admin-empty">ยังไม่มีข้อความจากผู้ใช้</div>';list.querySelectorAll('[data-id]').forEach(x=>x.onclick=()=>openTicket(x.dataset.id))}
function shell(){return `<div class="support-admin-view"><div class="support-admin-toolbar"><div><div class="eyebrow">DEKKHONGSHOP SUPPORT CENTER</div><h2>ติดต่อแอดมิน</h2><p>แชท Real-time · เสียงแจ้งเตือน · อ่านแล้ว · AI Assistant</p></div><button class="btn" id="supportRefresh">↻ รีเฟรช</button></div><div class="support-admin-layout"><aside class="support-admin-list"><div class="support-admin-list-head"><strong>Tickets</strong><span id="supportTicketCount">0</span></div><div id="supportAdminList"></div></aside><section class="support-admin-chat"><div id="supportAdminEmpty" class="support-admin-empty-main"><div>✦</div><strong>เลือก Ticket เพื่อเริ่มตอบ</strong><span>สถานะแอดมินจะเป็นออนไลน์เมื่อเปิดระบบ</span></div><div id="supportAdminThread" class="hidden"><header class="support-admin-thread-head"><div class="support-admin-user"><div id="supportAdminAvatar" class="support-admin-user-avatar">G</div><div><strong id="supportAdminSubject">—</strong><span id="supportAdminUser">—</span></div></div><select id="supportAdminStatus"><option value="open">รอแอดมิน</option><option value="pending">รอผู้ใช้</option><option value="closed">ปิดแล้ว</option></select></header><div class="support-admin-quick"><button data-q="สวัสดีครับ เดี๋ยวแอดมินตรวจสอบให้ครับ">รับเรื่อง</button><button data-q="รบกวนส่งรายละเอียดเพิ่มเติมให้แอดมินหน่อยครับ">ขอรายละเอียด</button><button data-q="แอดมินกำลังตรวจสอบและจะแจ้งผลให้ครับ">กำลังตรวจสอบ</button></div><div id="supportAdminMessages" class="support-admin-messages"></div><form id="supportAdminForm" class="support-admin-composer"><textarea id="supportAdminMessage" maxlength="2000" rows="1" placeholder="ตอบผู้ใช้..."></textarea><button type="submit">ส่ง</button></form></div></section></div></div>`}
async function openSupport(){const app=$('#app');if(!app)return;$('#supportNav')?.classList.add('active');$('#pageTitle').textContent='ติดต่อแอดมิน';$('#crumb').textContent='ติดต่อแอดมิน';app.innerHTML=shell();$('#supportRefresh').onclick=loadTickets;$('#supportAdminForm').onsubmit=sendReply;$('#supportAdminStatus').onchange=updateStatus;document.querySelectorAll('.support-admin-quick button').forEach(b=>b.onclick=()=>{$('#supportAdminMessage').value=b.dataset.q;$('#supportAdminMessage').focus()});$('#supportAdminMessage').addEventListener('input',()=>{presence();clearTimeout(typingStop);if(active)api('/api/support/admin/tickets/'+encodeURIComponent(active.id)+'/typing',{method:'POST',body:JSON.stringify({typing:true})}).catch(()=>{});typingStop=setTimeout(()=>{if(active)api('/api/support/admin/tickets/'+encodeURIComponent(active.id)+'/typing',{method:'POST',body:JSON.stringify({typing:false})}).catch(()=>{})},900)});await loadTickets();connectStream();}
async function openTicket(id){const d=await api('/api/support/admin/tickets/'+encodeURIComponent(id));active=d.ticket;renderList();$('#supportAdminEmpty').classList.add('hidden');$('#supportAdminThread').classList.remove('hidden');$('#supportAdminSubject').textContent=d.ticket.subject;$('#supportAdminUser').textContent=`${d.ticket.displayName||'Google User'} • ${d.ticket.email||''}`;$('#supportAdminAvatar').textContent=(d.ticket.displayName||'G').slice(0,1).toUpperCase();$('#supportAdminStatus').value=d.ticket.status;renderMessages(d.messages)}
function renderMessages(ms){const box=$('#supportAdminMessages');if(!box)return;box.innerHTML=ms.map(m=>`<div class="support-admin-message ${m.sender==='user'?'user':'admin'}"><div class="support-admin-number">#${m.number||''}</div><div class="support-admin-bubble">${m.sender==='ai'?'<b class="ai-label">AI</b> ':''}${esc(m.text).replace(/\n/g,'<br>')}</div><time>${new Date(m.createdAt).toLocaleString('th-TH',{hour:'2-digit',minute:'2-digit'})}${m.sender!=='user'?' · '+(m.readAt?'อ่านแล้ว':'รออ่าน'):''}</time></div>`).join('');box.scrollTop=box.scrollHeight}
async function sendReply(e){e.preventDefault();if(!active)return;const input=$('#supportAdminMessage'),message=input.value.trim();if(!message)return;input.value='';clearTimeout(typingStop);try{await api('/api/support/admin/tickets/'+encodeURIComponent(active.id)+'/typing',{method:'POST',body:JSON.stringify({typing:false})});await api('/api/support/admin/tickets/'+encodeURIComponent(active.id)+'/reply',{method:'POST',body:JSON.stringify({message})});await openTicket(active.id);await loadTickets();toast('ส่งข้อความแล้ว')}catch(err){input.value=message;toast(err.message,true)}}
function toast(message,error=false){const old=$('.support-admin-toast');if(old)old.remove();const x=document.createElement('div');x.className='support-admin-toast'+(error?' error':'');x.textContent=message;document.body.appendChild(x);setTimeout(()=>x.remove(),2600)}
async function updateStatus(){if(!active)return;try{await api('/api/support/admin/tickets/'+encodeURIComponent(active.id)+'/status',{method:'POST',body:JSON.stringify({status:$('#supportAdminStatus').value})});await openTicket(active.id);await loadTickets();toast('อัปเดตสถานะแล้ว')}catch(e){toast(e.message,true)}}
function connectStream(){if(stream)try{stream.close()}catch{};stream=new EventSource('/api/support/admin/stream');for(const ev of ['support:ticket-created','support:message-created','support:ticket-updated'])stream.addEventListener(ev,async e=>{const d=JSON.parse(e.data||'{}');if(ev==='support:message-created'&&d.message?.sender==='user'&&d.ticket?.id!==active?.id)try{new Audio('data:audio/wav;base64,UklGRiQAAABXQVZFZm10IBAAAAABAAEAESsAACJWAAACABAAZGF0YQAAAAA=').play()}catch{}await loadTickets();if(active){const x=await api('/api/support/admin/tickets/'+active.id).catch(()=>null);if(x){active=x.ticket;renderMessages(x.messages)}}});stream.onerror=()=>{try{stream.close()}catch{};setTimeout(()=>document.visibilityState!=='hidden'&&connectStream(),5000)}}
window.openSupportAdmin=openSupport;
function boot(){navButton();presence();setInterval(presence,10000);$('#supportNav')?.addEventListener('click',openSupport)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();