(()=>{
const $=s=>document.querySelector(s);let state=null;
async function api(u,o={}){const r=await fetch(u,{cache:'no-store',...o,headers:o.body instanceof FormData?{}:{'Content-Type':'application/json',...(o.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||`HTTP ${r.status}`);return d}
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const iconMap={
instagram:'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="12" r="4.2" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="17.5" cy="6.7" r="1.2" fill="currentColor"/></svg>',
tiktok:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14 4v10.2a4.8 4.8 0 1 1-4-4.7v3.1a1.8 1.8 0 1 0 1.8 1.8V4H14c.5 2.1 1.9 3.5 4 4v3.1c-1.5-.2-2.9-.8-4-1.8V4Z" fill="currentColor"/></svg>',
youtube:'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="2.5" y="5" width="19" height="14" rx="4" fill="currentColor"/><path d="M10 9l6 3-6 3V9Z" fill="#111"/></svg>',
facebook:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14 8h3V4h-3c-3.3 0-5 2-5 5v3H6v4h3v5h4v-5h3.3l.7-4H13V9c0-.7.3-1 1-1Z" fill="currentColor"/></svg>',
x:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 4h4.2l3.1 4.3L15.9 4H19l-5.3 6.1L19.5 20h-4.2l-3.7-5-4.1 5H4.4l5.7-6.7L5 4Z" fill="currentColor"/></svg>',
discord:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M19.5 5.2A16 16 0 0 0 15.8 4l-.5 1.1a14 14 0 0 0-6.6 0L8.2 4a16 16 0 0 0-3.7 1.2C2.2 8.7 1.6 12 2 15.2A15.8 15.8 0 0 0 6.7 18l1.1-1.5a9 9 0 0 1-1.6-.8l.4-.3a11.2 11.2 0 0 0 10.8 0l.4.3c-.5.3-1.1.6-1.6.8l1.1 1.5a15.8 15.8 0 0 0 4.7-2.8c.4-3.8-.3-7-2.5-10Z" fill="currentColor"/><circle cx="9" cy="12" r="1.3" fill="#111"/><circle cx="15" cy="12" r="1.3" fill="#111"/></svg>',
twitch:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 3h17v12l-5 5h-4l-3 3v-3H4V3Zm3 3v11h4v2l2-2h3l2-2V6H7Z" fill="currentColor"/><path d="M13 9h2v5h-2V9Zm-4 0h2v5H9V9Z" fill="currentColor"/></svg>',
github:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2.5a9.7 9.7 0 0 0-3.1 18.9c.5.1.7-.2.7-.5v-1.8c-2.8.6-3.4-1.2-3.4-1.2-.5-1.2-1.1-1.5-1.1-1.5-.9-.6.1-.6.1-.6 1 0 1.5 1 1.5 1 .9 1.5 2.4 1.1 3 .8.1-.6.4-1.1.7-1.3-2.2-.3-4.5-1.1-4.5-4.9 0-1.1.4-2 1-2.7-.1-.3-.4-1.3.1-2.7 0 0 .8-.3 2.8 1a9.7 9.7 0 0 1 5.1 0c2-1.3 2.8-1 2.8-1 .5 1.4.2 2.4.1 2.7.6.7 1 1.6 1 2.7 0 3.8-2.3 4.6-4.5 4.9.4.3.7.9.7 1.7v2.5c0 .3.2.6.7.5A9.7 9.7 0 0 0 12 2.5Z" fill="currentColor"/></svg>',
telegram:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m21 4-3 16c-.2 1.1-.8 1.4-1.6.9l-4.6-3.4-2.2 2.1c-.2.2-.4.4-.8.4l.3-4.7 8.5-7.7c.4-.4-.1-.6-.6-.2L6.5 14l-4.5-1.4c-1-.3-1-1 .2-1.5L19.8 3c.8-.3 1.5.2 1.2 1Z" fill="currentColor"/></svg>',
line:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.5 11.1c0 3.9-3.8 7.1-8.5 7.1-.7 0-1.4-.1-2.1-.2l-3.9 2.1.9-3.3c-2-1.3-3.4-3.3-3.4-5.7C3.5 7.2 7.3 4 12 4s8.5 3.2 8.5 7.1Z" fill="currentColor"/></svg>',
spotify:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9.5" fill="currentColor"/><path d="M7.2 10.1c3.2-1 6.8-.8 9.5.4M7.7 13c2.7-.7 5.7-.5 8 .4M8.5 15.7c2.1-.4 4.2-.2 6 .4" fill="none" stroke="#111" stroke-width="1.5" stroke-linecap="round"/></svg>',
globe:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9" fill="none" stroke="currentColor" stroke-width="2"/><path d="M3 12h18M12 3c2.5 2.6 3.7 5.6 3.7 9s-1.2 6.4-3.7 9c-2.5-2.6-3.7-5.6-3.7-9S9.5 5.6 12 3Z" fill="none" stroke="currentColor" stroke-width="1.5"/></svg>'};
function localIcon(link){if(link.iconAuto!==false&&link.iconKey)return iconMap[link.iconKey]||iconMap.globe;return `<span>${esc(link.icon||'')}</span>`}
function render(p){document.querySelector("#profileLoading")?.remove();state=p;document.title=p.seoTitle||p.name||'LinkBio';const root=document.documentElement;root.style.setProperty('--accent',p.accent||'#a855f7');root.style.setProperty('--bg',p.background||'#08080d');root.style.setProperty('--font-size',(p.fontSize||16)+'px');root.style.setProperty('--card-width',(p.cardWidth||480)+'px');document.body.style.fontFamily=`${p.font||'Prompt'},Inter,sans-serif`;const pc=p.profileCard||{};const pcRgb=c=>{c=String(c||'#000000').replace('#','');return c.length===6?`${parseInt(c.slice(0,2),16)},${parseInt(c.slice(2,4),16)},${parseInt(c.slice(4,6),16)}`:'0,0,0'};const pcAlpha=Math.min(1,Math.max(0,Number(pc.opacity??.08)));const pcBg=pc.enabled===false?'transparent':`rgba(${pcRgb(pc.backgroundColor||'#ffffff')},${pcAlpha})`;const pcBorderAlpha=Math.min(1,Math.max(0,Number(pc.borderOpacity??.15)));const pcBorder=`rgba(${pcRgb(pc.borderColor||'#ffffff')},${pcBorderAlpha})`;let pcShadow=pc.shadow!==false?`0 25px 70px rgba(0,0,0,${Number(pc.shadowOpacity??.35)*Number(pc.shadowIntensity??.35)})`:'';if(pc.glow&&Number(pc.glowIntensity||0)>0)pcShadow+=(pcShadow?', ':'')+`0 0 ${Math.round(60*Number(pc.glowIntensity))}px rgba(${pcRgb(pc.glowColor||'#8b5cf6')},${Math.min(1,Number(pc.glowIntensity)*.55)})`;root.style.setProperty('--pc-bg',pcBg);root.style.setProperty('--pc-border',pcBorder);root.style.setProperty('--pc-border-width',(pc.borderWidth??1)+'px');root.style.setProperty('--pc-radius',(pc.borderRadius??24)+'px');root.style.setProperty('--pc-blur',(pc.mode==='solid'?0:(pc.backdropBlur??pc.blur??20))+'px');root.style.setProperty('--pc-shadow',pcShadow||'none');root.style.setProperty('--pc-saturation',pc.mode==='solid'?'100%':'145%');root.style.setProperty('--pc-glow',pc.glowColor||'#8b5cf6');root.style.setProperty('--pc-glow-intensity',pc.glowIntensity??0);root.style.setProperty('--pc-hover-scale',pc.hoverScale?'1.025':'1');root.style.setProperty('--pc-animation-speed',(pc.animationSpeed??.5)+'s');root.style.setProperty('--pc-animation-intensity',pc.animationIntensity??1);root.dataset.pcAnimation=pc.animationEnabled===false?'none':(pc.animation||'fade');root.dataset.pcHover=pc.hoverEffect||'none';root.dataset.pcEnabled=pc.enabled===false?'false':'true';
if(window.renderLinkBioSticker){
  window.renderLinkBioSticker(pc.sticker||{
    enabled:false,
    preset:'sparkle',
    size:42,
    x:0,
    y:-10,
    rotation:0,
    opacity:1,
    animationSpeed:1
  });
}
$('#name').textContent=p.displayName||p.name||'Your Name';$('#username').textContent=p.username?'@'+p.username:'';$('#bio').textContent=p.bio||'';const adminBtn=$('#profileAdminBtn');if(adminBtn)adminBtn.onclick=()=>{const fab=document.querySelector('#supportFab');if(fab)fab.click();};$('#profileMeta').textContent=(p.statusEmoji||'●')+' '+(p.customStatus||p.status||'Online');$('#profileMeta').dataset.status=p.status||'Online';$('#avatar').src=p.avatar||'https://placehold.co/160x160/png?text=ME';
const badge=$('#badge');if(p.verified){badge.textContent='';badge.title='';badge.style.display='inline-flex';badge.style.color=p.verifiedNeon||p.verifiedColor||'#60a5fa';badge.style.opacity=p.verifiedOpacity??1;badge.style.fontSize=(p.verifiedSize||13)+'px';badge.style.borderRadius='0';badge.style.boxShadow='none';badge.dataset.animation=p.verifiedAnimation||'check';badge.style.animationDuration=(p.verifiedAnimationSpeed||1)+'s'}else{badge.textContent='';badge.title='';badge.style.display='none'}
const brand=$('#brandBadge');if(brand)brand.remove();
const bg=$('#bg'),a=p.appearance||{};if(a.backgroundType==='gradient')bg.style.background=`linear-gradient(${a.gradientAngle||135}deg,${(a.gradientColors||['#4b1c77','#08080d']).join(',')})`;else if(['image','gif'].includes(a.backgroundType))bg.style.background=`url('${a.backgroundImage||a.backgroundGif||''}') center/cover`;else if(a.backgroundType==='video'&&a.backgroundVideo){bg.innerHTML=`<video autoplay loop muted playsinline src="${esc(a.backgroundVideo)}"></video>`}else bg.style.background=a.backgroundColor||p.background||'#08080d';
if(window.LinkBioBackground){window.LinkBioBackground.setConfig(p.backgroundSettings||{enabled:false});}
const links=$('#links');links.innerHTML='';(p.links||[]).filter(x=>x.enabled!==false&&x.visible!==false&&(!x.startAt||Date.now()>=Date.parse(x.startAt))&&(!x.endAt||Date.now()<=Date.parse(x.endAt))).sort((a,b)=>(a.order??0)-(b.order??0)).forEach(x=>{const el=document.createElement('a');el.href=x.url;el.target=x.openNewTab===false?'_self':'_blank';el.rel='noopener noreferrer';el.dataset.hover=x.hover||'none';el.dataset.style=x.style||'glass';el.innerHTML=`<span class="link-label"><b class="site-icon" data-site="${esc(x.iconKey||'globe')}">${localIcon(x)}</b><span>${esc(x.title)}</span></span>${x.badge?`<small>${esc(x.badge)}</small>`:''}`;el.onclick=ev=>{api('/api/links/'+encodeURIComponent(x.id)+'/click',{method:'POST'}).catch(()=>{});if(x.confirm&&!confirm('ต้องการเปิดลิงก์นี้หรือไม่?'))ev.preventDefault()};links.appendChild(el)});
window.LinkBioVisualizer?.setConfig(p.visualizer||{});window.LinkBioPlayer?.setTracks(p.music||[])}
let loadTimer=null,loading=false;
async function load(retry=0){if(loading)return;loading=true;try{let sid=localStorage.getItem('linkbio_view_session');if(!sid){sid=crypto.randomUUID?.()||Date.now()+'-'+Math.random();localStorage.setItem('linkbio_view_session',sid)}if(!retry)api('/api/analytics/view',{method:'POST',body:JSON.stringify({sessionId:sid})}).catch(()=>{});const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),7000);const d=await api('/api/profile',{signal:controller.signal});clearTimeout(timeout);render(d.profile)}catch(e){console.warn('Profile load failed',e);if(retry<3){setTimeout(()=>load(retry+1),Math.min(1500*(retry+1),4000))}else if(!state)$('#links').innerHTML='<div class="error">กำลังเชื่อมต่อโปรไฟล์…</div>'}finally{loading=false}}
function scheduleLoad(){clearTimeout(loadTimer);loadTimer=setTimeout(()=>load(),80)}
$('#share')?.addEventListener('click',async()=>{try{if(navigator.share)await navigator.share({title:state?.name||'LinkBio',text:state?.bio||'',url:location.href});else await navigator.clipboard.writeText(location.href)}catch{}});
const dot=$('#mouseDot');if(dot&&matchMedia('(pointer:fine)').matches){let tx=innerWidth/2,ty=innerHeight/2,x=tx,y=ty;addEventListener('mousemove',e=>{tx=e.clientX;ty=e.clientY});const tick=()=>{x+=(tx-x)*.32;y+=(ty-y)*.32;dot.style.transform=`translate3d(${x}px,${y}px,0) translate(-50%,-50%)`;requestAnimationFrame(tick)};tick()}else dot?.remove();
addEventListener('storage',e=>{if(e.key==='linkbio_profile_updated')scheduleLoad()});const LinkBioUpdates='BroadcastChannel' in window?new BroadcastChannel('linkbio-updates'):null;LinkBioUpdates?.addEventListener('message',e=>{if(e.data?.type==='profile-updated')scheduleLoad()});
if('EventSource' in window){const stream=new EventSource('/api/profile/stream');stream.addEventListener('update',scheduleLoad);stream.onerror=()=>{try{stream.close()}catch{}setTimeout(()=>{if(document.visibilityState!=='hidden')location.reload()},5000)}}
addEventListener('online',()=>load());load();
})();
