import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js';
import { getAuth, GoogleAuthProvider, signInWithPopup, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js';

const firebaseConfig={apiKey:'AIzaSyCJpSjW6Kb79eDqilEeTfo-gFL_sdzyjHY',authDomain:'dekkhongbio.firebaseapp.com',projectId:'dekkhongbio',storageBucket:'dekkhongbio.firebasestorage.app',messagingSenderId:'769197699747',appId:'1:769197699747:web:390cc3e0648e50d5e6c516',measurementId:'G-GQHE59C1E0'};
const firebaseApp=initializeApp(firebaseConfig,'linkbio-support');
const auth=getAuth(firebaseApp);const provider=new GoogleAuthProvider();
let supportUser=null,activeTicket=null,stream=null;
const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const api=async(url,opt={})=>{const r=await fetch(url,{credentials:'same-origin',cache:'no-store',...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||`HTTP ${r.status}`);return d};
function mount(){if($('#supportRoot'))return;const root=document.createElement('div');root.id='supportRoot';root.innerHTML=`<button id="supportFab" class="support-fab" aria-label="ติดต่อแอดมิน"><span class="support-fab-icon">✦</span><span class="support-fab-text">ติดต่อแอดมิน</span><i id="supportUnread"></i></button><div id="supportOverlay" class="support-overlay" aria-hidden="true"><section id="supportPanel" class="support-panel" role="dialog" aria-modal="true"><div class="support-login" id="supportLogin"><div class="support-login-orb">✦</div><span class="support-kicker">LINKBIO SUPPORT</span><h2>กำลังเข้าสู่ศูนย์ช่วยเหลือ</h2><p>เข้าสู่ระบบด้วย Google เพื่อเริ่มติดต่อแอดมินและเก็บประวัติการสนทนา</p><button class="support-google" id="supportGoogle"><b>G</b><span>ดำเนินการต่อด้วย Google</span></button><small id="supportError"></small></div><div class="support-chat hidden" id="supportChat"><header class="support-head"><div class="support-agent"><div class="support-agent-avatar">LB</div><div><strong>Admin Support</strong><span><i></i> ออนไลน์</span></div></div><button id="supportClose" class="support-close">×</button></header><div class="support-body"><aside class="support-tickets"><div class="support-tickets-head"><strong>การติดต่อของฉัน</strong><button id="supportNew">＋</button></div><div id="supportTicketList"></div></aside><main class="support-conversation"><div id="supportEmpty" class="support-empty"><div>✦</div><strong>เลือกห้องแชท</strong><span>หรือเริ่มการติดต่อใหม่กับแอดมิน</span><button id="supportStart">เริ่มแชทใหม่</button></div><div id="supportThread" class="hidden"><div class="support-thread-head"><div><strong id="supportSubject">ติดต่อแอดมิน</strong><span id="supportStatus">รอแอดมิน</span></div><button id="supportCloseTicket">ปิด Ticket</button></div><div id="supportMessages" class="support-messages"></div><form id="supportForm" class="support-composer"><textarea id="supportMessage" maxlength="2000" rows="1" placeholder="พิมพ์ข้อความถึงแอดมิน..."></textarea><button type="submit">➤</button></form></div></main></div></div></section></div>`;document.body.appendChild(root);bind();}
async function googleLogin(){const err=$('#supportError');err.textContent='';try{const result=await signInWithPopup(auth,provider);const token=await result.user.getIdToken();const d=await api('/api/support/auth',{method:'POST',headers:{Authorization:'Bearer '+token}});supportUser=d.user;await openChat()}catch(e){err.textContent=e.message||'เข้าสู่ระบบไม่สำเร็จ';}}
async function openChat(){const overlay=$('#supportOverlay');overlay.classList.add('is-open');overlay.setAttribute('aria-hidden','false');document.body.classList.add('support-lock');setTimeout(()=>{$('#supportLogin').classList.add('hidden');$('#supportChat').classList.remove('hidden');loadTickets()},360);}
function closeChat(){const overlay=$('#supportOverlay');overlay.classList.remove('is-open');overlay.setAttribute('aria-hidden','true');document.body.classList.remove('support-lock');}
async function ensureSession(){try{const d=await api('/api/support/me');if(d.loggedIn){supportUser=d.user;return true}}catch{}return false}
async function loadTickets(){const d=await api('/api/support/tickets');$('#supportUnread').textContent=d.unread>0?String(Math.min(99,d.unread)):'';$('#supportUnread').style.display=d.unread?'grid':'none';const list=$('#supportTicketList');list.innerHTML=d.tickets.length?d.tickets.map(t=>`<button class="support-ticket ${activeTicket?.id===t.id?'active':''}" data-ticket="${esc(t.id)}"><span>${esc(t.subject)}</span><small>${t.status==='closed'?'ปิดแล้ว':t.status==='pending'?'รอคุณ':'รอแอดมิน'}${t.messageCount?` • ${t.messageCount} ข้อความ`:''}</small></button>`).join(''):'<div class="support-no-tickets">ยังไม่มีการติดต่อ</div>';
list.querySelectorAll('[data-ticket]').forEach(b=>b.onclick=()=>openTicket(b.dataset.ticket));}
async function openTicket(id){const d=await api('/api/support/tickets/'+encodeURIComponent(id));activeTicket=d.ticket;renderThread(d.ticket,d.messages);loadTickets()}
function renderThread(t,messages){$('#supportEmpty').classList.add('hidden');$('#supportThread').classList.remove('hidden');$('#supportSubject').textContent=t.subject;$('#supportStatus').textContent=t.status==='closed'?'ปิดแล้ว':t.status==='pending'?'แอดมินตอบแล้ว':'กำลังรอแอดมิน';$('#supportCloseTicket').style.display=t.status==='closed'?'none':'inline-flex';const box=$('#supportMessages');box.innerHTML=messages.map(m=>`<div class="support-message ${m.sender==='admin'?'admin':'user'}"><div class="support-bubble">${esc(m.text).replace(/\n/g,'<br>')}</div><time>${new Date(m.createdAt).toLocaleString('th-TH',{hour:'2-digit',minute:'2-digit'})}</time></div>`).join('');box.scrollTop=box.scrollHeight;}
async function newTicket(){const subject=prompt('หัวข้อที่ต้องการติดต่อแอดมิน','ติดต่อแอดมิน');if(subject===null)return;const message=prompt('พิมพ์ข้อความแรกที่ต้องการส่งถึงแอดมิน');if(!message?.trim())return;try{const d=await api('/api/support/tickets',{method:'POST',body:JSON.stringify({subject,message})});activeTicket=d.ticket;renderThread(d.ticket,d.messages);await loadTickets()}catch(e){alert(e.message)}}
async function sendMessage(e){e.preventDefault();if(!activeTicket||activeTicket.status==='closed')return;const input=$('#supportMessage');const message=input.value.trim();if(!message)return;input.value='';input.style.height='auto';try{const d=await api('/api/support/tickets/'+encodeURIComponent(activeTicket.id)+'/messages',{method:'POST',body:JSON.stringify({message})});activeTicket=d.ticket;const current=[...document.querySelectorAll('.support-message')].map(x=>({sender:x.classList.contains('admin')?'admin':'user'}));void current;const detail=await api('/api/support/tickets/'+encodeURIComponent(activeTicket.id));renderThread(detail.ticket,detail.messages);loadTickets()}catch(err){input.value=message;alert(err.message)}}
async function closeTicket(){if(!activeTicket||!confirm('ปิด Ticket นี้ใช่ไหม?'))return;try{const d=await api('/api/support/tickets/'+encodeURIComponent(activeTicket.id)+'/close',{method:'POST'});activeTicket=d.ticket;const detail=await api('/api/support/tickets/'+encodeURIComponent(activeTicket.id));renderThread(detail.ticket,detail.messages);loadTickets()}catch(e){alert(e.message)}}
function connectStream(){if(stream)try{stream.close()}catch{};stream=new EventSource('/api/support/stream');stream.addEventListener('support:message-created',async e=>{const d=JSON.parse(e.data||'{}');if(activeTicket?.id===d.ticket?.id){const detail=await api('/api/support/tickets/'+activeTicket.id).catch(()=>null);if(detail)renderThread(detail.ticket,detail.messages)}loadTickets()});stream.addEventListener('support:ticket-updated',async e=>{const d=JSON.parse(e.data||'{}');if(activeTicket?.id===d.ticket?.id){const detail=await api('/api/support/tickets/'+activeTicket.id).catch(()=>null);if(detail)renderThread(detail.ticket,detail.messages)}loadTickets()});stream.onerror=()=>{try{stream.close()}catch{};setTimeout(()=>supportUser&&document.visibilityState!=='hidden'&&connectStream(),5000)}}
function bind(){
 $('#supportFab').onclick=async()=>{if(await ensureSession()){await openChat();connectStream()}else{$('#supportOverlay').classList.add('is-open');$('#supportOverlay').setAttribute('aria-hidden','false');document.body.classList.add('support-lock')}};
 $('#supportGoogle').onclick=googleLogin;$('#supportClose').onclick=closeChat;$('#supportNew').onclick=newTicket;$('#supportStart').onclick=newTicket;$('#supportCloseTicket').onclick=closeTicket;$('#supportForm').onsubmit=sendMessage;
 $('#supportMessage').addEventListener('input',e=>{e.target.style.height='auto';e.target.style.height=Math.min(120,e.target.scrollHeight)+'px'});
 $('#supportOverlay').addEventListener('click',e=>{if(e.target.id==='supportOverlay')closeChat()});
}
mount();onAuthStateChanged(auth,async user=>{if(!user)return;try{const token=await user.getIdToken();const d=await api('/api/support/auth',{method:'POST',headers:{Authorization:'Bearer '+token}});supportUser=d.user}catch{}});
